from pathlib import Path
import csv


OUT_DIR = Path(r"C:\Users\itsumo\Desktop\paper\locomo_f1_open_reproducible_2026\qualified_papers")
OUT_PATH = OUT_DIR / "memory_paper_reading_notes_29.csv"


FIELDS = [
    "类别",
    "论文名",
    "年份/会议",
    "代码是否开源",
    "任务",
    "数据集",
    "指标",
    "一句话 motivation",
    "它批评现有方法什么",
    "Memory representation",
    "Memory update",
    "Memory retrieval",
    "Reasoning/generation",
    "Baselines",
    "主结果",
    "消融实验",
    "它真正的新点",
    "它可能的问题",
    "我能借鉴什么",
    "我能超过它的地方",
    "推荐精读分数_100",
    "来源链接",
    "代码链接",
]


def row(**kwargs):
    return {field: kwargs.get(field, "") for field in FIELDS}


rows = [
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="SimpleMem: Efficient Lifelong Memory for LLM Agents",
        **{
            "年份/会议": "2026 arXiv; submitted 2026-01-05",
            "代码是否开源": "是; GitHub: aiming-lab/SimpleMem",
            "任务": "面向长期交互的 LLM agent memory; 在有限上下文与有限 token 成本下支持长时对话问答与长期记忆检索。",
            "数据集": "LoCoMo; LongMemEval-S",
            "指标": "LoCoMo average F1; BLEU-1/LLM correctness; retrieval token cost; inference token cost; memory efficiency。",
            "一句话 motivation": "长期记忆系统不应该靠完整历史或昂贵迭代推理硬撑，而应该把历史压缩成高信息密度、可按意图检索的语义记忆。",
            "它批评现有方法什么": "批评 full-context 方式冗余且成本高; 批评普通 RAG/embedding retrieval 不能理解查询意图; 批评部分 agentic memory 依赖多轮迭代过滤噪声导致 token 与延迟开销过大。",
            "Memory representation": "把原始交互压缩成 compact memory units; 每个单元尽量上下文独立, 通过语义结构化压缩保留实体、时间、事件、关系等关键信息; 同时建立多视角索引, 便于后续语义、词面、符号线索混合召回。",
            "Memory update": "三阶段流程: Semantic Structured Compression 先把非结构化对话变为高密度记忆; Online Semantic Synthesis 在 session 内即时合并相关上下文, 减少重复与碎片; 新记忆进入时会和已有语义表示融合。",
            "Memory retrieval": "Intent-Aware Retrieval Planning 先判断查询意图与需要的检索深度, 再动态决定召回范围; 检索不是固定 top-k, 而是按问题复杂度组合 semantic/lexical/symbolic 线索。",
            "Reasoning/generation": "最终把压缩后的高密度 evidence context 输入 LLM 生成答案; 重点是减少上下文噪声和 token 量, 而不是让 LLM 在长原文中自己找证据。",
            "Baselines": "LoCoMo/Full Context, ReadAgent, MemoryBank, MemGPT, A-Mem, LightMem, Mem0",
            "主结果": "论文报告在 LoCoMo 上平均 F1 提升约 26.4%, 同时推理阶段 token 消耗最高可减少约 30 倍; 主要贡献是性能和成本同时改善。",
            "消融实验": "围绕结构化压缩、在线语义合成、意图感知检索等组件做 ablation; 结论是压缩提高信息密度, synthesis 降低重复, retrieval planning 对复杂问题收益明显。",
            "它真正的新点": "把 memory 问题讲成信息密度和检索意图匹配问题, 不是单纯堆图结构或堆长上下文; 工程实现也相对清楚。",
            "它可能的问题": "所谓 semantic lossless 仍依赖 LLM 抽取质量; 一旦压缩阶段丢失细节, 后续很难恢复; 对 temporal conflict 和 evidence sufficiency 的显式处理不够强。",
            "我能借鉴什么": "可以借鉴多视角索引、意图感知检索、压缩后再检索的实验故事; 也适合作为你自己方法里的高效 memory backbone。",
            "我能超过它的地方": "加 raw evidence fallback、证据充分性 verifier、时间冲突版本管理; 让系统不仅高效, 还能说明证据是否足够、是否过期、是否互相冲突。",
            "推荐精读分数_100": "95",
            "来源链接": "https://arxiv.org/abs/2601.02553",
            "代码链接": "https://github.com/aiming-lab/SimpleMem",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="TiMem: Temporal-Hierarchical Memory Consolidation for Long-Horizon Conversational Agents",
        **{
            "年份/会议": "2026 arXiv; submitted 2026-01-06",
            "代码是否开源": "是; GitHub: TiMEM-AI/timem",
            "任务": "长时对话 agent 的时间连续性和个性化记忆; 重点是把不断增长的对话组织成可逐层抽象的时间层级结构。",
            "数据集": "LoCoMo; LongMemEval-S",
            "指标": "LoCoMo F1/LLM-Judge/Rouge-L; LongMemEval-S accuracy; recalled memory length; efficiency。",
            "一句话 motivation": "长期对话中的用户状态和 persona 是随时间演化的, memory 系统必须把 temporal continuity 当作一等公民。",
            "它批评现有方法什么": "批评现有 memory 框架缺少跨层级的时间结构, 导致记忆碎片化、persona 表示不稳定、长时个性化容易漂移。",
            "Memory representation": "核心是 Temporal Memory Tree, 由 segment/daily/session/weekly/profile 等层级组成; 低层保留局部事实和事件, 高层形成更稳定的 persona/偏好表示。",
            "Memory update": "通过 semantic-guided consolidation 在不同时间层级之间合并记忆; 不需要微调模型, 主要依赖 LLM 抽象和层级整合。",
            "Memory retrieval": "复杂度感知 recall: 简单问题查较低层或局部记忆, 复杂/长期/人格相关问题上升到更高层级; 在精度和召回长度之间做平衡。",
            "Reasoning/generation": "答案阶段使用按问题复杂度召回的层级记忆; 通过 temporal tree 提供更稳定的时间上下文和 persona 背景。",
            "Baselines": "MemoryBank, Mem0, A-Mem, MemoryOS, MemOS",
            "主结果": "论文报告 LoCoMo 约 75.30%, LongMemEval-S 约 76.88%; 在 LoCoMo 上召回记忆长度减少约 52.20%。",
            "消融实验": "主要验证 TMT 层级结构、semantic-guided consolidation、complexity-aware recall 的贡献; 还用 manifold/persona 分析展示表征分离与稳定性。",
            "它真正的新点": "把 memory consolidation 显式做成时间层级树, 故事比单纯摘要或图检索更贴合长期对话。",
            "它可能的问题": "层级设计和合并规则较依赖 prompt; 高层 persona 抽象可能过早固化用户状态; 冲突/证据充分性仍不是主轴。",
            "我能借鉴什么": "可以借鉴时间层级和 query complexity routing, 用来解释为什么不同问题应该查不同粒度的记忆。",
            "我能超过它的地方": "加入记忆版本控制与 evidence-level verification, 让时间层级不仅能总结过去, 还能判断新旧状态冲突。",
            "推荐精读分数_100": "86",
            "来源链接": "https://arxiv.org/abs/2601.02845",
            "代码链接": "https://github.com/TiMEM-AI/timem",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="MAGMA: A Multi-Graph based Agentic Memory Architecture for AI Agents",
        **{
            "年份/会议": "2026 arXiv; submitted 2026-01-06",
            "代码是否开源": "是; GitHub: FredJiang0324/MAGMA",
            "任务": "为 memory-augmented generation 提供多关系图记忆, 支持长时推理、时间/因果/实体关系检索。",
            "数据集": "LoCoMo; LongMemEval",
            "指标": "LoCoMo F1; BLEU-1; LLM judge; long-horizon reasoning accuracy; efficiency。",
            "一句话 motivation": "单一向量库会把时间、因果、实体关系混在一起, 导致 retrieved evidence 与 query intent 对不齐。",
            "它批评现有方法什么": "批评基于语义相似度的 monolithic memory store 只知道 what occurred, 不知道 why/when/how connected; 也批评图方法缺少多视角解耦。",
            "Memory representation": "维护向量库加四类 relation graphs: semantic graph, temporal graph, causal graph, entity graph; 同一记忆项在不同图视角下有不同边和拓扑。",
            "Memory update": "写入采用 fast/slow 双流: Synaptic Ingestion 做低延迟初步接入, Asynchronous Consolidation 做计算更重的关系补全和图结构深化。",
            "Memory retrieval": "Intent-Aware Router 根据查询类型选择图视角; Adaptive Topological Retrieval 在对应关系图上 traversal; Context Synthesizer 组织最终上下文。",
            "Reasoning/generation": "用检索到的多图路径构造结构化 narrative context; 让 LLM 不只看相似文本, 还能看到时间、因果、实体连接。",
            "Baselines": "Full Context/LoCoMo, A-Mem, Nemori, MemoryOS",
            "主结果": "论文报告在 LoCoMo 和 LongMemEval 上超过已有 agentic memory 系统, 特别强调 reasoning path 的透明性和 query-adaptive retrieval。",
            "消融实验": "围绕不同 graph view、router、topological retrieval、fast/slow update 做组件分析; 用于证明多图解耦比单一向量/单图更有效。",
            "它真正的新点": "把 memory representation 解耦为多张正交关系图, 并把检索写成 policy-guided traversal。",
            "它可能的问题": "多图构建成本高; 因果边质量依赖 LLM 判断; 图过多可能带来维护复杂度和错误传播。",
            "我能借鉴什么": "可以借鉴 query intent 到 graph view 的路由思想; 也可借鉴 fast/slow 写入降低在线延迟。",
            "我能超过它的地方": "把多图 traversal 后的证据做 sufficiency/conflict 检查; 少建全量多图, 改为按问题动态构建必要关系。",
            "推荐精读分数_100": "87",
            "来源链接": "https://arxiv.org/abs/2601.03236",
            "代码链接": "https://github.com/FredJiang0324/MAGMA",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="Membox: Weaving Topic Continuity into Long-Range Memory for LLM Agents",
        **{
            "年份/会议": "2026 arXiv; submitted 2026-01-07",
            "代码是否开源": "是; GitHub: nnnoidea/Membox",
            "任务": "长时人机对话中的主题连续性建模; 重点解决 per-turn 存储破坏叙事和因果流的问题。",
            "数据集": "LoCoMo",
            "指标": "LoCoMo F1; BLEU; category-level F1; token/memory base statistics。",
            "一句话 motivation": "长期对话不是孤立句子的集合, memory unit 应该在写入时就保留同一主题下的连续事件流。",
            "它批评现有方法什么": "批评 fragmentation-compensation 范式: 先把对话切碎再靠 embedding 找回连贯性, 这会不可逆地破坏 narrative/causal flow。",
            "Memory representation": "Topic Loom 在滑动窗口中识别连续同主题 turn, 将其封装为 memory boxes; Trace Weaver 再把不同时间出现的相关 boxes 串成 long-range event timeline traces。",
            "Memory update": "在线监控 topic continuity; 当主题段结束时 sealed box; 后续重复主题通过 trace links 连接, 形成跨时间的宏观主题轨迹。",
            "Memory retrieval": "检索单位从单句/单 turn 变为 topic-coherent box 与 trace; 对 temporal/multi-hop 问题能一次召回更完整的事件链。",
            "Reasoning/generation": "LLM 基于检索到的 memory boxes 和 traces 生成答案; 依靠 topic coherence 减少 missing link。",
            "Baselines": "LoCoMo/Full Context, ReadAgent, MemoryBank, MemGPT, A-Mem, Mem0",
            "主结果": "论文报告在 LoCoMo temporal reasoning 上最高约 68% F1 improvement, 且使用更少上下文 token。",
            "消融实验": "分析不同 topic box/trace 设计和 retrieval depth; 结果支持 topic continuity 对 temporal 和 multi-hop 问题贡献更大。",
            "它真正的新点": "把写入粒度从 turn/fact 改成 topic-continuous memory box, 先保住叙事连续性再检索。",
            "它可能的问题": "topic segmentation 错误会影响整箱记忆; box 过大可能引入噪声, 过小又退化成 fragment。",
            "我能借鉴什么": "适合借鉴 topic-aware segmentation, 用在你自己的 memory construction 前端。",
            "我能超过它的地方": "加入 evidence sufficiency 来判断 box 是否足够; 引入 raw-turn pointer 和 conflict handling 防止 box summary 掩盖细节。",
            "推荐精读分数_100": "84",
            "来源链接": "https://arxiv.org/abs/2601.03785",
            "代码链接": "https://github.com/nnnoidea/Membox",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="HiMem: Hierarchical Long-Term Memory via Topic-Aware Event-Surprise Dual-Channel Segmentation for LLM Agents",
        **{
            "年份/会议": "2026 arXiv; submitted 2026-01-10",
            "代码是否开源": "是; GitHub: jojopdq/HiMem",
            "任务": "长时对话中的层级记忆构建、检索和动态更新; 关注自适应、可扩展、自演化记忆。",
            "数据集": "LoCoMo; long-horizon dialogue benchmarks",
            "指标": "LoCoMo F1; GPT-score/LLM evaluation; consistency; efficiency。",
            "一句话 motivation": "长期记忆系统既要保留具体 episode, 又要形成稳定 note knowledge, 并能在失败后自我修正。",
            "它批评现有方法什么": "批评现有长期记忆适应性、扩展性、自演化不足; 也批评单层记忆难以同时保留原始事件和抽象知识。",
            "Memory representation": "两类核心记忆: Episode Memory 保存认知一致的事件片段; Note Memory 保存多阶段抽取得到的稳定知识; 二者通过语义链接构成层级结构。",
            "Memory update": "Topic-Aware Event-Surprise Dual-Channel Segmentation 决定 episode 边界; 多阶段信息抽取生成 note; conflict-aware Memory Reconsolidation 会根据检索反馈修订或补充记忆。",
            "Memory retrieval": "提供 hybrid retrieval 和 best-effort retrieval; 可先从抽象 note 查起, 必要时下钻到具体 episode。",
            "Reasoning/generation": "答案阶段结合 abstract knowledge 和 concrete event evidence, 以减少只用摘要或只用原文的偏差。",
            "Baselines": "Mem0, SeCom, A-Mem",
            "主结果": "论文报告在长时对话基准上超过代表性 baselines, 并强调 accuracy、consistency、efficiency 同时提升。",
            "消融实验": "验证 hierarchical organization、semantic alignment、conflict-aware updating 的必要性; 说明记忆层级和更新机制都对鲁棒性有贡献。",
            "它真正的新点": "把 episode-note 层级和 conflict-aware reconsolidation 放在同一框架中, 比只做检索更像持续学习记忆系统。",
            "它可能的问题": "组件多, 实现复杂; reconsolidation 若判断错误可能把旧错误写得更牢; 需要清晰的失败定位机制。",
            "我能借鉴什么": "可以借鉴 episode/note 双层结构和 retrieval failure as learning signal 的叙事。",
            "我能超过它的地方": "把 reconsolidation 改成可审计的 evidence repair: 明确 missing/conflicting/outdated 三类失败并分别修复。",
            "推荐精读分数_100": "88",
            "来源链接": "https://arxiv.org/abs/2601.06377",
            "代码链接": "https://github.com/jojopdq/HiMem",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="MemWeaver: Weaving Hybrid Memories for Traceable Long-Horizon Agentic Reasoning",
        **{
            "年份/会议": "2026 arXiv; submitted 2026-01-24",
            "代码是否开源": "是; GitHub: Chengkai-Huang/MemWeaver_code",
            "任务": "面向长时 agentic reasoning 的 traceable memory; 支持 temporal consistency、multi-hop reasoning 和 evidence-grounded reuse。",
            "数据集": "LoCoMo",
            "指标": "LoCoMo token-level F1; BLEU-1; context length/token cost; category-level reasoning accuracy。",
            "一句话 motivation": "长期记忆不能只存抽象知识, 还必须能回到原始证据, 否则多跳和时间推理容易失真。",
            "它批评现有方法什么": "批评 unstructured retrieval 和 coarse abstraction 导致 temporal conflict、brittle reasoning、traceability 差。",
            "Memory representation": "三层混合记忆: Graph Memory 组织实体关系和时间事实; Experience Memory 抽象重复交互模式; Passage Memory 保存原文证据; 三者通过实体/语义链接打通。",
            "Memory update": "对新经历进行 tri-layer consolidation: 抽取事实进入 graph, 归纳重复模式进入 experience, 保留原文 passage 作为证据锚点。",
            "Memory retrieval": "Dual-channel retrieval 同时召回结构化知识和 supporting evidence; Graph 提供推理路径, Passage 提供可追溯原文。",
            "Reasoning/generation": "LLM 使用 compact context, 其中既有结构化关系也有证据文本; 目标是回答可被证据支撑。",
            "Baselines": "Full Context/LoCoMo, MemoryBank, ReadAgent, A-Mem",
            "主结果": "论文报告显著提升 multi-hop 与 temporal reasoning, 同时相比 long-context baseline 输入上下文长度减少超过 95%。",
            "消融实验": "围绕 Graph/Experience/Passage 三类 memory 和 dual-channel retrieval 做 ablation, 证明 traceable evidence 与结构化推理互补。",
            "它真正的新点": "不是只做 graph 或 summary, 而是把结构化推理和原始证据追溯并列为核心能力。",
            "它可能的问题": "三层一致性维护成本高; experience abstraction 的边界不易评估; passage 链接如果太粗会影响证据定位。",
            "我能借鉴什么": "非常适合借鉴 graph + raw passage 的 evidence grounding 设计。",
            "我能超过它的地方": "加入证据充分性判断和冲突诊断, 让 dual-channel retrieval 不只是召回, 还能决定是否需要继续查。",
            "推荐精读分数_100": "91",
            "来源链接": "https://arxiv.org/abs/2601.18204",
            "代码链接": "https://github.com/Chengkai-Huang/MemWeaver_code",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="E-mem: Multi-Agent Based Episodic Context Reconstruction for LLM Agent Memory",
        **{
            "年份/会议": "2026 arXiv; submitted 2026-01-30",
            "代码是否开源": "是; GitHub: dog-last/E-mem",
            "任务": "用 multi-agent episodic context reconstruction 解决长上下文推理中的上下文完整性问题。",
            "数据集": "LoCoMo; streaming HotpotQA",
            "指标": "LoCoMo F1; BLEU-1; token cost; multi-hop/temporal category scores。",
            "一句话 motivation": "很多 memory 预处理在压缩或结构化时破坏了原始上下文, System-2 式推理更需要重建 episode 而不是只检索碎片。",
            "它批评现有方法什么": "批评 embedding/graph/summary 等预处理会造成 destructive de-contextualization, 断开复杂顺序依赖和局部语境。",
            "Memory representation": "异构层级 multi-agent 架构; 多个 assistant agents 各自维护未压缩的 episodic memory contexts, master agent 负责全局规划与证据聚合。",
            "Memory update": "通过 assistant 维护局部 episode, 尽量不在写入阶段过度压缩; 重点把原始上下文保存在可激活的 segment 中。",
            "Memory retrieval": "master 生成或调整 probe, 激活相关 assistant; assistant 在自己的 episode 内局部推理并返回 context-aware evidence; master 迭代聚合全局 trace。",
            "Reasoning/generation": "推理过程是 master-assistant 多步证据汇总, 而不是一次性 retrieve-then-answer; 对 multi-hop 和 ultra-long context 有优势。",
            "Baselines": "Long Context, RAG, A-Mem, Mem0, MemoryOS, LightMem, GAM",
            "主结果": "论文报告 LoCoMo overall F1 超过 54, 比 GAM 高约 7.75%, 同时 token cost 降低超过 70%。",
            "消融实验": "分析 assistant 数量、局部 episode 激活、master planning、模型规模和 token cost; 证明上下文重建而非单纯检索是收益来源。",
            "它真正的新点": "把 memory retrieval 改成多 agent 的 episodic reconstruction, 强调局部上下文完整性。",
            "它可能的问题": "多 agent 调度成本和实现复杂度较高; 若 assistant 分段不准, master 可能拿不到关键 evidence; 本科复现可能要做简化。",
            "我能借鉴什么": "借鉴 active evidence reconstruction 和局部 episode reasoning, 不一定照搬 multi-agent 全套。",
            "我能超过它的地方": "做更轻量的 query-aware episode activation, 加 evidence sufficiency stop rule, 降低多 agent 调度成本。",
            "推荐精读分数_100": "89",
            "来源链接": "https://arxiv.org/abs/2601.21714",
            "代码链接": "https://github.com/dog-last/E-mem",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="MemSkill: Learning and Evolving Memory Skills for Self-Evolving Agents",
        **{
            "年份/会议": "2026 arXiv; submitted 2026-02-03",
            "代码是否开源": "是; GitHub: ViktorAxelsen/MemSkill",
            "任务": "把 memory extraction/consolidation/pruning 从手工固定流程改成可学习、可演化的 skills。",
            "数据集": "LoCoMo; LongMemEval; HotpotQA; ALFWorld",
            "指标": "LoCoMo F1/LLM-Judge; LongMemEval accuracy; HotpotQA QA performance; ALFWorld task success; generalization。",
            "一句话 motivation": "不同任务需要不同的记忆操作, 固定手工 memory pipeline 太僵硬, 应该让 agent 学会并演化 memory skills。",
            "它批评现有方法什么": "批评现有系统把抽取、合并、删除等操作硬编码, 对多样交互模式适应性差, 也难从失败案例中改进。",
            "Memory representation": "memory 不只是条目集合, 还包含一个 skill bank; 每个 skill 是可复用的记忆处理例程, 指导 LLM 如何抽取、整合或修剪信息。",
            "Memory update": "controller 选择少量 relevant skills; LLM executor 生成 skill-guided memories; designer 周期性检查 hard cases, 通过 LLM 改写旧 skill 或提出新 skill; controller 继续训练。",
            "Memory retrieval": "检索本身不是唯一重点; 核心是写入/更新质量由 skill selection 控制, 从而让后续 retrieval 面对更适配任务的 memory store。",
            "Reasoning/generation": "答案阶段使用 skill-guided memory; 框架强调从下游失败反向优化记忆构建, 使 generation 输入更可靠。",
            "Baselines": "No Memory, Chain-of-Notes, ReadAgent, MemoryBank, A-Mem, Mem0, LangMem, MemoryOS",
            "主结果": "论文报告在 LoCoMo、LongMemEval、HotpotQA、ALFWorld 上均超过强 baseline, 且能跨设置泛化。",
            "消融实验": "验证 skill controller、skill evolution、hard-case review、exploration 等组件; 展示 evolved skills 的案例分析。",
            "它真正的新点": "把 memory 操作本身参数化为可学习技能, 从失败中演化 memory system。",
            "它可能的问题": "训练和演化流程复杂; 需要 hard-case 标注/反馈设计; 复现成本高于纯 prompt/RAG 方法。",
            "我能借鉴什么": "可以借鉴 failure-driven memory repair, 但本科项目可做简化版 self-audit 而不是完整 RL skill learning。",
            "我能超过它的地方": "把 skill evolution 聚焦到 LoCoMo 错误类型: missing evidence、temporal conflict、multi-hop broken link, 降低泛化框架复杂度。",
            "推荐精读分数_100": "92",
            "来源链接": "https://arxiv.org/abs/2602.02474",
            "代码链接": "https://github.com/ViktorAxelsen/MemSkill",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="BudgetMem: Learning Query-Aware Budget-Tier Routing for Runtime Agent Memory",
        **{
            "年份/会议": "2026 arXiv; submitted 2026-02-09",
            "代码是否开源": "是; GitHub: ViktorAxelsen/BudgetMem",
            "任务": "运行时 agent memory 的性能-成本可控路由; 让不同查询按预算选择不同复杂度的 memory modules。",
            "数据集": "LoCoMo; LongMemEval; HotpotQA",
            "指标": "LoCoMo F1; LLM-Judge; answer accuracy; token/cost; latency; accuracy-cost frontier。",
            "一句话 motivation": "不是每个问题都值得用最贵的 memory 处理, memory 系统应该能按 query 显式控制性能与成本权衡。",
            "它批评现有方法什么": "批评 offline query-agnostic memory construction 会浪费计算, 也可能丢掉当前 query 关键的信息; 批评 runtime 方法缺少可控成本机制。",
            "Memory representation": "把 memory processing 拆成多个 modules, 每个 module 有 LOW/MID/HIGH 三档 budget tier; 记忆表示与处理复杂度绑定。",
            "Memory update": "根据 implementation/reasoning/capacity 三种 tiering strategy 调整写入/抽取/容量; 高预算可用更复杂模型或更深入推理。",
            "Memory retrieval": "轻量 neural router 在运行时根据 query 选择各模块预算档位; router 由 reinforcement learning 训练, 目标是性能和成本平衡。",
            "Reasoning/generation": "generation 使用由预算路由决定的 memory context; 高预算追求准确, 低预算追求更低延迟/成本。",
            "Baselines": "ReadAgent, MemoryBank, A-Mem, LangMem, Mem0, MemoryOS, LightMem",
            "主结果": "论文报告高预算设置下超过强 baseline; 低预算下得到更好的 accuracy-cost frontier。",
            "消融实验": "比较 implementation/reasoning/capacity 三种 tiering; 分析 router、budget setting、不同任务复杂度对效果和成本的影响。",
            "它真正的新点": "把 memory 方法从单点性能竞争转成可控成本曲线竞争, 很适合真实系统。",
            "它可能的问题": "RL router 训练增加门槛; 如果论文目标是纯 LoCoMo F1, 成本控制故事可能分散主线。",
            "我能借鉴什么": "借鉴 query-aware routing 和 budget-aware ablation; 可为你的方法增加 cost/latency 维度。",
            "我能超过它的地方": "不做复杂 RL, 用规则/LLM classifier 先做 question type 和 evidence sufficiency 路由, 更易实现且故事更聚焦。",
            "推荐精读分数_100": "86",
            "来源链接": "https://arxiv.org/abs/2602.06025",
            "代码链接": "https://github.com/ViktorAxelsen/BudgetMem",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="REMem: A Retrieval-Enhanced Memory Framework for Long-Horizon Conversational Agents",
        **{
            "年份/会议": "2026 ICLR / arXiv; submitted 2026-02-18",
            "代码是否开源": "是; GitHub: intuit-ai-research/REMem",
            "任务": "episodic recollection and reasoning; 从长交互历史中回忆具体经历并跨事件推理。",
            "数据集": "LoCoMo; REALTALK; Complex-TR; episodic memory benchmarks",
            "指标": "F1; BLEU-1; LLM-Judge; refusal behavior for unanswerable questions; inference token cost。",
            "一句话 motivation": "语言 agent 的 memory 过度语义化, 但人类式长期记忆需要具体 episode、时空上下文和跨事件推理。",
            "它批评现有方法什么": "批评现有方法忽略 episodicity, 缺少显式事件建模, 或过分依赖简单 retrieval 而不是复杂推理。",
            "Memory representation": "Hybrid memory graph: time-aware gists 与 facts 并存; gist 保留事件上下文, fact 提供细粒度事实; synonymy/temporal/entity 等边支持跨节点推理。",
            "Memory update": "Indexing phase 将 experiences 转换为 memory graph; 建立 gist/fact 节点和链接; 为后续 agentic inference 准备工具可访问结构。",
            "Memory retrieval": "Agentic retriever 使用 curated tools 做多步检索; 包含 semantic retrieve、lexical retrieve、graph traversal 等, 可迭代选择工具。",
            "Reasoning/generation": "REMem-I 多步选择工具并推理; REMem-S 是单步 embedding retrieval 对照; 对 unanswerable questions 更强调拒答鲁棒性。",
            "Baselines": "Full Context, Qwen3-Embed-8B, NV-Embed-v2, Mem0, Graphiti, HippoRAG 2",
            "主结果": "论文报告相比 SOTA memory systems 在 episodic recollection 上绝对提升约 3.4%, 在 episodic reasoning 上绝对提升约 13.4%; 同时拒答更稳健。",
            "消融实验": "Table 5 对 w/o Gists、w/o Facts、w/o Synonymy edges、w/o semantic retrieve、w/o lexical retrieve 做 ablation; gists 和 synonymy edges 对 LoCoMo 影响明显。",
            "它真正的新点": "将 episodic memory 形式化为 gist+fact hybrid graph, 再用 tool-using agentic retriever 做推理式检索。",
            "它可能的问题": "agentic retrieval 成本较高; graph 构建依赖抽取质量; 多工具流程实现比普通 RAG 复杂。",
            "我能借鉴什么": "强烈建议精读 gist/fact 区分、tool ablation、unanswerable/refusal 设计。",
            "我能超过它的地方": "用 evidence sufficiency 作为工具选择和停止条件, 减少无效迭代; 加 temporal conflict versioning 处理更新事实。",
            "推荐精读分数_100": "94",
            "来源链接": "https://arxiv.org/abs/2602.13530",
            "代码链接": "https://github.com/intuit-ai-research/REMem",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="AriadneMem: Threading the Maze of Lifelong Memory for LLM Agents",
        **{
            "年份/会议": "2026 arXiv; submitted 2026-03-04",
            "代码是否开源": "是; GitHub: LLM-VLM-GSL/AriadneMem",
            "任务": "固定 context budget 下的 lifelong memory; 解决 disconnected evidence 与 state updates 两类长期对话错误。",
            "数据集": "LoCoMo",
            "指标": "Average F1; Multi-Hop F1; BLEU; token count; runtime/cost。",
            "一句话 motivation": "长期记忆失败常常不是没存, 而是证据散落无法连起来, 或新旧状态冲突没有被图结构表达。",
            "它批评现有方法什么": "批评 raw-log retrieval 缺少结构连接; 批评 iterative reasoning 用多轮 LLM 查询模拟连接, 成本高; 批评过度压缩会丢掉逻辑路径。",
            "Memory representation": "结构化 memory graph; offline 阶段用 entropy-aware gating 过滤低信息消息; conflict-aware coarsening 合并静态重复, 保留 state transitions 为 temporal edges。",
            "Memory update": "构建阶段先过滤噪声, 再抽取记忆并做冲突感知合并; 对 evolving information 不直接覆盖, 而是保留转移边。",
            "Memory retrieval": "在线阶段先检索候选事实, 再执行 algorithmic bridge discovery 重建缺失逻辑路径; 避免昂贵 LLM iterative planning。",
            "Reasoning/generation": "single-call topology-aware synthesis 将图拓扑和桥接路径转化为答案上下文; 把推理负担尽量下沉到 graph layer。",
            "Baselines": "LoCoMo/Full Context, ReadAgent, MemoryBank, MemGPT, A-Mem, LightMem, Mem0, SimpleMem",
            "主结果": "论文报告 GPT-4o 上 Multi-Hop F1 比强 baseline 提升约 15.2%, Average F1 提升约 9.0%, runtime 降低约 77.8%, 仅使用约 497 context tokens。",
            "消融实验": "围绕 entropy-aware gating、conflict-aware coarsening、bridge discovery、topology-aware synthesis 做分析; 证明桥接和冲突保留是主要收益。",
            "它真正的新点": "用图算法显式补 disconnected evidence, 并把 state update 表示成 temporal transition, 这和 LoCoMo 多跳/时间题非常对口。",
            "它可能的问题": "依赖图抽取质量; algorithmic bridge 的规则边界可能不适合开放域问题; 对 raw evidence 追溯的细节需核查。",
            "我能借鉴什么": "你的 baseline 里建议重点精读; 可以借鉴 disconnected evidence + state update 这两个问题定义。",
            "我能超过它的地方": "加 evidence sufficiency verifier: bridge discovery 后判断证据是否足够; 对冲突状态做 active/outdated/uncertain 三态版本。",
            "推荐精读分数_100": "96",
            "来源链接": "https://arxiv.org/abs/2603.03290",
            "代码链接": "https://github.com/LLM-VLM-GSL/AriadneMem",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="D-MEM: Dopamine-Gated Agentic Memory via Reward Prediction Error Routing",
        **{
            "年份/会议": "2026 arXiv; submitted 2026-03-17",
            "代码是否开源": "是; GitHub: london-and-tequila/dmem",
            "任务": "为 agentic memory 加写入门控, 在噪声长期对话中降低 update 成本和上下文污染。",
            "数据集": "LoCoMo; LoCoMo-Noise; possibly long-term dialogue noisy settings",
            "指标": "LoCoMo F1; BLEU-1; token/API cost; write latency; noise robustness。",
            "一句话 motivation": "不应该每句话都触发昂贵的全局记忆演化, 只有高 surprise/高长期价值的信息才值得进入 slow memory。",
            "它批评现有方法什么": "批评 A-Mem 类 append-and-evolve-all 同步架构有 O(N^2) 写入成本、API token 无界增长, 且噪声会污染上下文。",
            "Memory representation": "Fast/Slow 双系统; fast buffer/cache 处理低价值日常输入; slow global knowledge graph 负责高价值长期结构调整。",
            "Memory update": "Critic Router 评估 Information Entropy/Surprise 和 Long-term Utility; 低 RPE 输入绕过或缓存, 高 RPE 输入触发 dopamine release, 激活 deep memory evolution。",
            "Memory retrieval": "常规查询可先访问 fast buffer 和 slow graph; 重点不是检索算法新, 而是通过门控让 slow memory 更干净。",
            "Reasoning/generation": "答案使用更少噪声污染的 memory; 在 noisy long dialogue 下更稳定。",
            "Baselines": "LoCoMo/Full Context, ReadAgent, MemoryBank, MemGPT, A-Mem",
            "主结果": "论文强调在 LoCoMo/LoCoMo-Noise 上保持或提升 F1, 同时显著降低写入延迟和 token 成本; 具体优势集中在噪声鲁棒性。",
            "消融实验": "通常包括去掉 critic router、去掉 surprise/utility 信号、不同噪声比例和 fast/slow routing 策略比较。",
            "它真正的新点": "把长期 memory 写入看作 reward prediction error gated process, 解决写入成本和噪声污染。",
            "它可能的问题": "gate 错判会导致关键记忆丢失; RPE/utility 设计主观; 与 LoCoMo 标准设置的直接可比性要注意。",
            "我能借鉴什么": "可以借鉴 write-time filtering/gating, 作为你方法中的 cost-control 或 memory admission 子模块。",
            "我能超过它的地方": "让 gate 不只看 surprise, 还看未来 query evidence value; 对被绕过信息保留 raw backup 以降低漏记风险。",
            "推荐精读分数_100": "83",
            "来源链接": "https://arxiv.org/abs/2603.14597",
            "代码链接": "https://github.com/london-and-tequila/dmem",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="MemMA: Coordinating the Memory Cycle through Multi-Agent Reasoning and In-Situ Self-Evolution",
        **{
            "年份/会议": "2026 arXiv; submitted 2026-03-19",
            "代码是否开源": "是; GitHub: ventr1c/memma",
            "任务": "协调 memory construction、retrieval、utilization 和 repair, 做 plug-and-play 的 self-evolving memory cycle。",
            "数据集": "LoCoMo; multiple LLM backbones/storage backends",
            "指标": "F1; BLEU-1; ACC/LLM judge; ablation across storage backends and backbones。",
            "一句话 motivation": "memory 系统不能把构建、检索、使用当成彼此孤立的步骤, 下游失败应该反向修复 memory bank。",
            "它批评现有方法什么": "批评 forward path strategic blindness: 构建和检索靠局部启发式; 批评 backward path 缺少监督: 下游失败很少转化为直接 memory repair。",
            "Memory representation": "框架本身可插入不同 storage backend; 记忆由 Memory Manager 管理, 并受 Meta-Thinker 的结构化策略指导。",
            "Memory update": "forward path 中 Meta-Thinker 指导 Memory Manager 构建记忆; backward path 中生成 probe QA、验证当前 memory, 将失败转化为 repair actions 后再定稿。",
            "Memory retrieval": "Query Reasoner 在 Meta-Thinker 指导下做 iterative retrieval; 检索不是盲搜, 而是带策略的多步查询。",
            "Reasoning/generation": "多 agent 分工: Meta-Thinker 负责策略, Memory Manager 负责构建/修复, Query Reasoner 负责查询与回答。",
            "Baselines": "Full Text, Naive RAG, LangMem, Mem0, A-Mem, LightMem",
            "主结果": "论文报告在 LoCoMo 上跨多个 LLM backbone 超过 baselines, 并且能提升三种不同 storage backend。",
            "消融实验": "验证 Meta-Thinker、Query Reasoner、probe QA self-evolution、repair actions 等模块; 也比较不同 backbone/backend。",
            "它真正的新点": "把 memory pipeline 变成闭环: 构建-检索-验证-修复, 很适合讲 self-evolving memory。",
            "它可能的问题": "多 agent 流程重, token 和实现成本高; probe QA 质量会限制修复效果; 复现变量多。",
            "我能借鉴什么": "强烈建议借鉴 in-situ self-evolution 和 failure-to-repair 的故事。",
            "我能超过它的地方": "把闭环简化成 evidence audit: 只针对 LoCoMo 错误类型做最小修复, 更可控、更容易写本科论文。",
            "推荐精读分数_100": "93",
            "来源链接": "https://arxiv.org/abs/2603.18718",
            "代码链接": "https://github.com/ventr1c/memma",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="Omni-SimpleMem: Autoresearch-Guided Discovery of Lifelong Multimodal Agent Memory",
        **{
            "年份/会议": "2026 arXiv; submitted 2026-04-01",
            "代码是否开源": "是; code linked through aiming-lab/SimpleMem",
            "任务": "用 autonomous research pipeline 自动发现/改进多模态 lifelong memory framework。",
            "数据集": "LoCoMo; Mem-Gallery",
            "指标": "LoCoMo F1; Mem-Gallery F1; experiment trajectory; bug-fix/architecture/prompt contribution。",
            "一句话 motivation": "lifelong multimodal memory 的设计空间太大, 靠人手调参和传统 AutoML 难以有效探索。",
            "它批评现有方法什么": "批评人工设计 memory architecture、retrieval strategy、prompt、data pipeline 的探索范围有限; 传统 AutoML 难处理系统级交互。",
            "Memory representation": "结果系统基于 SimpleMem 思路扩展到 multimodal setting; 具体结构由 autoresearch pipeline 经多轮实验发现, 包含过滤、检索、prompt 和数据管线修复。",
            "Memory update": "更新机制随自动发现的 architecture/pipeline 改动而变化; 论文更关注自动科研流程如何诊断和修改 memory system。",
            "Memory retrieval": "通过自动实验迭代优化 retrieval strategy 和 prompt; 不是单一明确的新检索算法。",
            "Reasoning/generation": "使用改进后的 memory context 完成 LoCoMo/Mem-Gallery 问答; 重点是 autoresearch 找到可提升 F1 的系统改动。",
            "Baselines": "Naive baseline, SimpleMem",
            "主结果": "从 LoCoMo naive F1=0.117 出发, pipeline 约 50 次实验后报告 LoCoMo F1 +411%, Mem-Gallery +214%; bug fix、architecture change、prompt engineering 的贡献大于纯超参调优。",
            "消融实验": "以 discovery type/taxonomy 分析 bug fixes、architecture changes、prompt engineering、data pipeline 等贡献。",
            "它真正的新点": "新点不完全是 memory algorithm, 而是用 autonomous research 自动发现 memory 系统改进。",
            "它可能的问题": "对你做算法改进而言故事可能偏系统自动化; 结果可解释性和人工复现路径需要细读代码。",
            "我能借鉴什么": "借鉴 error diagnosis、bug-fix contribution、实验自动化记录方式; 不建议作为主 baseline。",
            "我能超过它的地方": "把自动发现的经验落成一个明确可解释算法, 例如 evidence-calibrated retrieval, 更适合毕业论文讲清楚。",
            "推荐精读分数_100": "76",
            "来源链接": "https://arxiv.org/abs/2604.01007",
            "代码链接": "https://github.com/aiming-lab/SimpleMem",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="LightMem: Lightweight LLM Agent Memory with Small Language Models",
        **{
            "年份/会议": "2026 arXiv; submitted 2026-04-09",
            "代码是否开源": "是; GitHub: zjunlp/LightMem",
            "任务": "用 small language models 驱动轻量级 agent memory, 降低在线检索、写入和长期整合成本。",
            "数据集": "LoCoMo; long-horizon memory benchmarks",
            "指标": "LoCoMo F1; latency; retrieval time; end-to-end time; efficiency across model scales。",
            "一句话 motivation": "大模型在线反复做 memory 操作很贵, 但纯向量检索又不稳; 小模型可以承担高频 memory 控制与筛选。",
            "它批评现有方法什么": "批评 retrieval-only 系统 query construction/candidate filtering 弱; 批评多次大模型在线 memory 操作带来长期延迟累积。",
            "Memory representation": "STM/MTM/LTM 三层: STM 保存即时上下文, MTM 保存可复用交互摘要, LTM 保存离线整合的长期知识; memory unit 带 user identifier 支持多用户隔离。",
            "Memory update": "online Writer SLM 增量写 MTM; offline large-context model 做 long-term abstraction 和 consolidation; 在线与离线解耦。",
            "Memory retrieval": "online Controller SLM 做 intent/query planning 和 budget allocation; vector coarse retrieval 后由 Selector SLM 做 metadata prefilter 和 semantic-consistency reranking。",
            "Reasoning/generation": "答案阶段使用 Selector 输出的 top-k memory; 目标是在低延迟下提供足够相关的记忆。",
            "Baselines": "LoCoMo/Full Context, ReadAgent, MemoryBank, MemGPT, A-Mem",
            "主结果": "论文报告在 LoCoMo 上平均 F1 比 A-Mem 高约 2.5, retrieval median latency 约 83ms, end-to-end 约 581ms。",
            "消融实验": "通常围绕 Controller/Selector/Writer、STM/MTM/LTM、offline consolidation、不同 SLM 尺寸和 top-k 做 ablation。",
            "它真正的新点": "把 memory control 交给多个专门 SLM, 把大模型从高频在线路径中拿掉。",
            "它可能的问题": "SLM 选择/重排质量可能限制上限; 与 2025 LightMem 名称容易混淆; 对复杂 evidence sufficiency 的处理仍不充分。",
            "我能借鉴什么": "借鉴 online/offline 解耦和 SLM reranker, 对本科工程实现很友好。",
            "我能超过它的地方": "增加问题类型识别和证据充分性判断, 让 selector 不只筛相似, 还能判断是否足够回答。",
            "推荐精读分数_100": "90",
            "来源链接": "https://arxiv.org/abs/2604.07798",
            "代码链接": "https://github.com/zjunlp/LightMem",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="HeLa-Mem: Hebbian Learning and Associative Memory for LLM Agents",
        **{
            "年份/会议": "2026 arXiv; submitted 2026-04-21",
            "代码是否开源": "是; GitHub: ReinerBRO/HeLa-Mem",
            "任务": "用 Hebbian learning 风格的动态关联图改善长期 agent memory 的连续性和联想召回。",
            "数据集": "LoCoMo",
            "指标": "LoCoMo F1; BLEU-1; category-level scores; context token usage。",
            "一句话 motivation": "人类记忆不是静态数据库, 相关经历会因共同激活而逐渐加强连接; agent memory 也需要动态关联结构。",
            "它批评现有方法什么": "批评 unstructured embedding retrieval 只靠表面语义相似, 缺少 association、consolidation、spreading activation 这类生物记忆机制。",
            "Memory representation": "双层组织: episodic memory graph 通过 co-activation 动态强化边; semantic memory store 由 Reflective Agent 对高连接 memory hubs 做 Hebbian Distillation 得到结构化知识。",
            "Memory update": "新经历写入 episodic graph; 相关节点共同激活时增强连接; 周期性或条件触发 reflective distillation, 把稳定关联压缩进 semantic store。",
            "Memory retrieval": "结合语义相似和 learned associations; spreading activation 可从一个线索扩散到相关 episode/semantic knowledge。",
            "Reasoning/generation": "答案阶段接收由相似性和联想激活共同选出的 memories; 目标是保留发展中的关系连续性。",
            "Baselines": "LoCoMo/Full Context, ReadAgent, MemoryBank, MemGPT, A-Mem, Mem0, LightMem, MemoryOS",
            "主结果": "论文报告在 LoCoMo 四类问题上均有优势, 并使用显著更少 context tokens。",
            "消融实验": "通常验证 association、Hebbian Distillation、spreading activation、dual-level memory 各自贡献。",
            "它真正的新点": "把 Hebbian association 引入 agent memory graph, 从 repeated co-activation 中学习关系强度。",
            "它可能的问题": "生物启发故事好讲但实现细节需警惕过拟合; association 强化可能把偶然相关也连强; 冲突和证据充分性不是核心。",
            "我能借鉴什么": "可以借鉴动态边权和 spreading activation 用于补充图检索。",
            "我能超过它的地方": "用 evidence verifier 过滤错误联想; 把边权更新和时间有效性绑定, 防止旧偏好持续激活。",
            "推荐精读分数_100": "84",
            "来源链接": "https://arxiv.org/abs/2604.16839",
            "代码链接": "https://github.com/ReinerBRO/HeLa-Mem",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="AnchorMem: Anchored Facts with Associative Contexts for Building Memory in Large Language Models",
        **{
            "年份/会议": "2026 arXiv; submitted 2026-04-21",
            "代码是否开源": "是; GitHub: RayNeo-AI-2025/AnchorMem",
            "任务": "长期对话 memory 中兼顾细粒度检索和原始上下文完整性; 尤其适合解决 fact extraction 丢上下文的问题。",
            "数据集": "LoCoMo; evaluated across closed/open-source LLM backbones",
            "指标": "F1; BLEU; ACC/LLM judge; runtime/calls/update tokens; ablation by question type。",
            "一句话 motivation": "检索应该用原子事实做 anchor, 但生成答案时必须回到完整原始 context, 否则摘要会稀释关键细节。",
            "它批评现有方法什么": "批评 A-Mem/Mem0 类频繁重写和摘要过度依赖, 会淡化上下文细节、遮蔽检索特征。",
            "Memory representation": "将 retrieval unit 与 generation context 解耦: atomic facts 作为 retrieval anchors; raw chunks 作为 immutable context; Associative Event Graph 用高阶 event links 绑定相关 facts。",
            "Memory update": "从交互历史抽取 atomic facts; 保留原始 chunks 不重写; 建立 fact-context 连接和 event-level associative links。",
            "Memory retrieval": "先把 query anchor 到相关 facts/events, 再通过 anchors 找到对应 raw chunks 和 event context; 兼顾精确检索和上下文恢复。",
            "Reasoning/generation": "最终答案基于 reconstructed raw chunks/events, 而不是只基于压缩事实; 有利于减少细节丢失。",
            "Baselines": "Naive RAG, HippoRAG 2, Mem0, A-Mem, MemoryOS, LightMem",
            "主结果": "论文报告在多种 backbone 上显著超过 baselines; ablation 中去掉 raw context 后平均 F1 从 50.57 降到 21.13, 说明上下文恢复是核心。",
            "消融实验": "清晰 ablation: w/o Context, w/o FCU, w/o AEG; 还分析 inter-fact similarity threshold 和 fact neighbor 数对性能/效率的影响。",
            "它真正的新点": "把 fact anchor 和 immutable raw context 明确解耦, 是很适合你讲 evidence reconstruction 的设计。",
            "它可能的问题": "atomic fact 抽取质量仍关键; raw chunks 召回过多会带来成本; event graph 超参需要调。",
            "我能借鉴什么": "非常建议精读; 可直接借鉴 anchor-to-raw-evidence 机制。",
            "我能超过它的地方": "加 sufficiency verifier 判断 raw context 是否足够; 对冲突 facts 做 version status, 避免 anchor 到过期事实。",
            "推荐精读分数_100": "94",
            "来源链接": "https://arxiv.org/abs/2604.17377",
            "代码链接": "https://github.com/RayNeo-AI-2025/AnchorMem",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="HiGMem: A Hierarchical and LLM-Guided Memory System for Long-Term Conversational Agents",
        **{
            "年份/会议": "2026 arXiv; submitted 2026-04-22",
            "代码是否开源": "是; GitHub: ZeroLoss-Lab/HiGMem",
            "任务": "LoCoMo10 长期对话证据检索; 用 event summary 作为高层 anchor 引导 LLM 选择值得读的 turns。",
            "数据集": "LoCoMo10",
            "指标": "LoCoMo10 F1; category-level F1; retrieved turns count/efficiency。",
            "一句话 motivation": "向量检索会返回大量表面相似但没用的 turns, 需要先读高层事件再决定哪些底层 turn 值得看。",
            "它批评现有方法什么": "批评包括层级 memory 在内的许多系统仍只靠 vector similarity, 造成 evidence set bloated、precision 低、answer-stage context cost 高。",
            "Memory representation": "两层 event-turn memory: Turn node 保存原始对话 turn 及 metadata; Event node 保存 summary 和 fact sheet, 并通过索引链接到相关 turn。",
            "Memory update": "新 turn 写入后生成 metadata; 系统判断其所属 event 或创建新 event; 维护 event 到 turn 的双向链接和 provenance traceability。",
            "Memory retrieval": "先检索 event summaries 和 semantic turn candidates; LLM 根据 event summary 预测哪些 related turns 值得读; 最后形成小而可靠的 evidence set。",
            "Reasoning/generation": "答案阶段使用被 LLM-guided retrieval 精选的 turns; 依靠 event summary 减少无关上下文。",
            "Baselines": "ReadAgent, MemoryBank, A-Mem, Full Context/LoCoMo",
            "主结果": "论文报告在 LoCoMo10 五类问题中四类取得最佳 F1; adversarial F1 相比 A-Mem 从 0.54 提升到 0.78, 且检索 turns 少一个数量级。",
            "消融实验": "围绕 event layer、turn layer、LLM-guided retrieval、vector-only 对照做分析; 重点验证高层 event anchor 对 precision 的提升。",
            "它真正的新点": "简单但有效: event summary 不是最终答案材料, 而是 guiding anchor, 用来指导读哪些 raw turns。",
            "它可能的问题": "LoCoMo10 是小子集, 需注意与完整 LoCoMo 可比性; LLM 预测 turns 可能受 prompt 影响。",
            "我能借鉴什么": "借鉴 high-level anchor -> low-level evidence 的两阶段检索, 实现成本低。",
            "我能超过它的地方": "加入 evidence gap diagnosis: 如果选出的 turns 不足, 自动说明缺什么并二次检索。",
            "推荐精读分数_100": "88",
            "来源链接": "https://arxiv.org/abs/2604.18349",
            "代码链接": "https://github.com/ZeroLoss-Lab/HiGMem",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="EviMem: Evidence-Gap-Driven Iterative Retrieval for Long-Term Conversational Memory",
        **{
            "年份/会议": "2026 arXiv; submitted 2026-04-30",
            "代码是否开源": "是; GitHub: AIGeeksGroup/EviMem",
            "任务": "长期对话记忆中的 temporal/multi-hop evidence retrieval; 通过显式诊断 evidence gap 进行迭代检索。",
            "数据集": "LoCoMo",
            "指标": "Judge Accuracy/G-EVAL; token-level F1; ROUGE-L; BERTScore; latency。",
            "一句话 motivation": "多跳和时间问题失败的关键不是第一次没检索到, 而是系统不知道当前 evidence set 缺什么。",
            "它批评现有方法什么": "批评 single-pass retrieval 在 temporal/multi-hop 问题上失败; 批评现有 iterative methods 根据生成内容或文档信号盲目改写 query, 没有显式诊断缺失证据。",
            "Memory representation": "LaceMem 三层 coarse-to-fine hierarchy: Index layer 存 semantic tuples 用于快速搜索; Edge layer 支持 multi-hop expansion; Raw layer 保存完整对话细节用于 grounded generation。",
            "Memory update": "先构建 layered conversational evidence memory; 将 atomic tuples、edges、raw details 对齐, 让 sufficiency evaluator 能看到细粒度缺口。",
            "Memory retrieval": "IRIS closed-loop retrieval: 每轮评估 accumulated evidence 为 EXACT/INFERRABLE/PARTIAL, 生成缺失信息诊断; 用 diagnosis 生成 refined query; 同时保留 original-question path 防止 drift。",
            "Reasoning/generation": "如果证据足够则回答; 如果多轮后仍不足则显式 abstain, 避免 hallucination; generation 基于 Raw layer ground evidence。",
            "Baselines": "Single-pass, MIRIX",
            "主结果": "论文报告相对 MIRIX, temporal Judge Accuracy 约 73.3%→81.6%, multi-hop 约 65.9%→85.2%, latency 低约 4.5 倍; 另补充 token-level F1/ROUGE/BERTScore。",
            "消融实验": "验证 sufficiency classifier 的 reliability/commitment precision/confidence discriminability; 对 IRIS/LaceMem、dual-path retrieval、entity fact tracking 做分析。",
            "它真正的新点": "把检索改成 evidence gap diagnosis driven, 这和你想做的可解释、可实现改进高度吻合。",
            "它可能的问题": "主指标偏 G-EVAL/Judge, token-level F1 是补充; baseline 数较少; sufficiency prompt 质量决定系统稳定性。",
            "我能借鉴什么": "强烈建议精读; 可以直接借鉴 EXACT/INFERRABLE/PARTIAL 和 missing evidence diagnosis。",
            "我能超过它的地方": "把它和 A-Mem/SimpleMem/AnchorMem 的 memory structure 结合, 并在完整 LoCoMo F1 上扩大 baseline 对比。",
            "推荐精读分数_100": "97",
            "来源链接": "https://arxiv.org/abs/2604.27695",
            "代码链接": "https://github.com/AIGeeksGroup/EviMem",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="MRAgent: Memory-Augmented Agents for Long-Horizon Reasoning",
        **{
            "年份/会议": "2026 ICLR / OpenReview",
            "代码是否开源": "是; GitHub: Ji-shuo/MRAgent",
            "任务": "长历史 agent 推理中的 active memory access; 让检索随中间证据动态改变。",
            "数据集": "LoCoMo; LongMemEval",
            "指标": "LoCoMo F1; LLM-Judge; LongMemEval accuracy; token/runtime cost。",
            "一句话 motivation": "静态 retrieve-then-reason 管线太僵硬, 复杂问题需要边推理边重建记忆路径。",
            "它批评现有方法什么": "批评 similarity-based/passive retrieval 只根据原始 query 一次性选 memory, 无法根据已经发现的证据调整访问策略。",
            "Memory representation": "Cue-Tag-Content graph: fine-grained cue 指向 associative tags, tags 再连接 memory content; tags 作为语义桥梁, 让 LLM 先选择路径再读内容。",
            "Memory update": "将 memory units 组织成 cue/tag/content 三层关联图; 写入时生成 cues/tags 并建立关联, 重点支持后续路径探索和剪枝。",
            "Memory retrieval": "Active reconstruction: 每一步根据 query 和 accumulated evidence 选择下一批 memory units; 迭代探索/剪枝 retrieval paths, 避免无约束图扩展。",
            "Reasoning/generation": "LLM reasoning 直接嵌入 memory access, 中间证据影响下一步检索; 最终基于主动重建的 evidence chain 答案生成。",
            "Baselines": "RAG, LangMem, A-Mem, MemoryOS, Mem0",
            "主结果": "论文报告在 LoCoMo 和 LongMemEval 上相对强 baseline 最高提升约 23%, 同时降低 token 和 runtime cost。",
            "消融实验": "分析主动重建、Cue-Tag-Content graph、路径剪枝、被动检索对照; 还给出 active policy 表达能力强于 passive retrieval 的理论分析。",
            "它真正的新点": "把 memory retrieval 形式化为 sequential decision process, 从被动检索升级为主动重建。",
            "它可能的问题": "图构造和主动策略实现复杂; 迭代过程可能受 LLM 判断波动影响; 需要控制成本。",
            "我能借鉴什么": "非常适合借鉴 active retrieval 的问题定义, 尤其是 accumulated evidence 决定下一步检索。",
            "我能超过它的地方": "把 active retrieval 的动作选择改为 evidence gap/sufficiency 驱动, 并加 temporal conflict handling。",
            "推荐精读分数_100": "95",
            "来源链接": "https://openreview.net/forum?id=YPoHy6lgKP",
            "代码链接": "https://github.com/Ji-shuo/MRAgent",
        },
    ),
    row(
        类别="2026 LoCoMo F1 open/reproducible",
        论文名="KeyMem: Graph-Augmented Vector Retrieval for Persistent Conversational Memory in LLM Agents",
        **{
            "年份/会议": "2026 aiXiv; 2026-03-26",
            "代码是否开源": "是; GitHub: g0dA/KeyMem",
            "任务": "持久对话记忆中的 graph-augmented vector retrieval; 保留 raw turns 同时支持 multi-hop/temporal 查找。",
            "数据集": "LoCoMo-10",
            "指标": "Overall token F1; Recall; MultiHop F1; Temporal F1。",
            "一句话 motivation": "事实压缩会损失信息, 纯向量检索又做不好多跳和时间问题; 应该保留原始 turn 并用图扩展补足关系。",
            "它批评现有方法什么": "批评 Mem0 fact extraction 丢失 temporal/emotional/nuanced context; 批评纯 vector retrieval 对跨 turn 指代、多跳、非相邻记忆聚合不足。",
            "Memory representation": "把 raw conversational turns 存在 knowledge graph 中; turn/fragment 与关键词、实体、时间和关联边连接, 保持 full information fidelity。",
            "Memory update": "写入时用 lightweight reference resolution state machine 处理指代消解; 构建 fragment clusters 和 source-aware metadata。",
            "Memory retrieval": "dual-path architecture: keyword vector search 找候选, graph traversal 做 Fragment-based multi-hop expansion; source-aware scoring 使用 query-local normalization, 不需预设超参。",
            "Reasoning/generation": "把召回的 raw turns/fragment evidence 交给 LLM 回答; 依靠 raw storage 避免摘要损失。",
            "Baselines": "Mem0, SimpleMem",
            "主结果": "LoCoMo-10 Overall F1=0.609, Recall=0.847; 相比 mem0 F1=0.372 提升约 63.7%, Recall=0.480 提升约 76.5%; Temporal F1 提升尤其大。",
            "消融实验": "围绕 fragment expansion、source-aware scoring、reference resolution、graph traversal 对照做分析; 重点证明 graph+vector 比单一路径稳。",
            "它真正的新点": "方法相对朴素但可实现: raw turn fidelity + graph expansion + source-aware scoring。",
            "它可能的问题": "只在 LoCoMo-10 上验证, baseline 较少; graph 构建简单时可能不如复杂 agentic memory。",
            "我能借鉴什么": "适合借鉴为一个轻量 raw-evidence backend; 也适合本科实现。",
            "我能超过它的地方": "扩大到 full LoCoMo, 加强问题类型路由和 evidence sufficiency, 与 A-Mem/SimpleMem/AriadneMem 做公平对比。",
            "推荐精读分数_100": "90",
            "来源链接": "https://aixiv.science/abs/aixiv.260326.000002",
            "代码链接": "https://github.com/g0dA/KeyMem",
        },
    ),
    row(
        类别="高频 baseline / 基准项",
        论文名="A-MEM: Agentic Memory for LLM Agents",
        **{
            "年份/会议": "2025 NeurIPS; arXiv submitted 2025-02-17",
            "代码是否开源": "是; evaluation: WujiangXu/AgenticMemory; system: agiresearch/A-mem",
            "任务": "为 LLM agents 动态组织长期记忆; 让 memory network 能随新记忆进入而自动建立链接和演化。",
            "数据集": "LoCoMo; 多个 foundation models; 长期 agent memory evaluation",
            "指标": "LoCoMo F1/ME/SBERT 等; category-level QA; 多模型平均表现。",
            "一句话 motivation": "memory 系统不应只有固定存取操作, 应该像 Zettelkasten 一样动态建立互联知识网络。",
            "它批评现有方法什么": "批评现有 memory 只有基础存储检索, 或 graph database 结构固定; 固定操作和结构限制跨任务适应性。",
            "Memory representation": "新增 memory 会变成 comprehensive note, 包含 contextual description、keywords、tags 等结构属性; memory notes 之间通过相似性和语义关系建立链接, 形成动态 network。",
            "Memory update": "写入新 memory 时检索相关历史 memory, 建立 meaningful links; 新记忆还能触发已有记忆的 contextual representation/attributes 更新, 即 memory evolution。",
            "Memory retrieval": "基于动态 memory network 和结构化 note 属性检索相关记忆; 相比纯 embedding 更强调 agentic organization。",
            "Reasoning/generation": "LLM 使用检索出的 memory notes 和关联上下文生成答案; 适配多种 LLM backbone。",
            "Baselines": "LoCoMo, ReadAgent, MemoryBank, MemGPT, None 等",
            "主结果": "作为 2026 LoCoMo memory 论文中被使用次数最高的 baseline; arXiv 摘要称在六个 foundation models 上优于已有 SOTA baselines。",
            "消融实验": "关注 note attributes、动态链接、memory evolution 等组件; 证明 agentic organization 不是简单向量库。",
            "它真正的新点": "把 Zettelkasten 的 note-link-evolve 思想引入 LLM agent memory, 成为后续工作的核心参照系。",
            "它可能的问题": "写入和演化成本较高; 链接质量依赖 LLM; 对证据充分性、时间冲突、raw evidence trace 的处理不是重点。",
            "我能借鉴什么": "必须精读, 因为它是你 baseline 的核心; 可以借鉴 note schema 和动态链接。",
            "我能超过它的地方": "针对 A-Mem 的弱点做 story: 写入太重、链接不等于证据足够、旧事实冲突难处理。",
            "推荐精读分数_100": "98",
            "来源链接": "https://arxiv.org/abs/2502.12110",
            "代码链接": "https://github.com/agiresearch/A-mem; https://github.com/WujiangXu/AgenticMemory",
        },
    ),
    row(
        类别="高频 baseline / 基准项",
        论文名="Mem0: Building Production-Ready AI Agents with Scalable Long-Term Memory",
        **{
            "年份/会议": "2025 arXiv; submitted 2025-04-28",
            "代码是否开源": "是; GitHub: mem0ai/mem0",
            "任务": "生产级 AI agent 长期记忆层; 动态抽取、整合和检索长期对话中的显著信息。",
            "数据集": "LOCOMO benchmark; production-oriented evaluations",
            "指标": "LLM-as-a-Judge; LoCoMo category scores; latency; token cost; p95 latency。",
            "一句话 motivation": "LLM 固定上下文窗口让长期多会话对话不一致, 需要可扩展、低延迟、低成本的持久记忆层。",
            "它批评现有方法什么": "批评 full-context 成本高且不可部署; 普通 RAG 缺少长期个性化和动态更新; 现有 memory 平台在延迟/成本/准确率上难平衡。",
            "Memory representation": "基础 Mem0 把对话转为 salient facts/preferences 等记忆条目并存入向量库; enhanced variant 使用 graph-based memory representation 捕获关系结构。",
            "Memory update": "每轮或阶段性从对话中抽取、合并、更新用户偏好/事实; 生产系统强调 CRUD 式 memory operations 和可扩展存储。",
            "Memory retrieval": "根据当前 query 从长期记忆库召回相关 facts; graph variant 利用关系结构增强召回。",
            "Reasoning/generation": "检索出的记忆作为个性化上下文输入 LLM, 让多会话回答保持一致。",
            "Baselines": "Memory systems, RAG variants, full-context, open-source/proprietary memory platforms",
            "主结果": "论文报告 Mem0 相对 OpenAI memory 在 LLM-as-Judge 上有约 26% relative improvement; p95 latency 降低约 91%, token cost 节省超过 90%。",
            "消融实验": "比较 base Mem0 与 graph memory variant, 不同 RAG chunk/k/full-context 类 baseline, 以及成本-延迟指标。",
            "它真正的新点": "不是最学术的结构创新, 但非常工程化、可部署、可作为工业 memory baseline。",
            "它可能的问题": "fact extraction 容易丢上下文细节; 单步检索对 temporal/multi-hop 较弱; 对原始 evidence trace 不够强。",
            "我能借鉴什么": "适合做可复现 baseline 和工程接口; 也可以借鉴显著事实抽取。",
            "我能超过它的地方": "强调 Mem0 的事实抽取损失, 用 raw evidence reconstruction、multi-hop expansion、temporal conflict 作为超越点。",
            "推荐精读分数_100": "96",
            "来源链接": "https://arxiv.org/abs/2504.19413",
            "代码链接": "https://github.com/mem0ai/mem0",
        },
    ),
    row(
        类别="高频 baseline / 基准项",
        论文名="Evaluating Very Long-Term Conversational Memory of LLM Agents / LoCoMo",
        **{
            "年份/会议": "2024 arXiv; submitted 2024-02-27",
            "代码是否开源": "是; 数据和 benchmark repo: snap-research/locomo",
            "任务": "构建并评估非常长期对话记忆 benchmark; 包含 QA、event summarization、多模态对话生成。",
            "数据集": "LoCoMo: very long-term conversations, average about 300 turns/9K tokens, up to 35 sessions; persona and temporal event graphs; LoCoMo10 subset commonly used。",
            "指标": "QA F1; BLEU/ROUGE-like text metrics; LLM judge; event summarization; multimodal dialogue generation metrics。",
            "一句话 motivation": "已有长期开放域对话评估通常只有少量 session, 无法测试真正长时的时间、因果和人物关系记忆。",
            "它批评现有方法什么": "批评长上下文 LLM 和 RAG 在非常长的多 session 对话中的效果尚未被充分评估; 现有数据缺乏长程时间/因果动态。",
            "Memory representation": "作为 benchmark 不提出 memory 方法; 数据由 persona、temporal event graphs、长对话和图片反应组成; Full Context/LoCoMo baseline 指把完整历史作为上下文。",
            "Memory update": "无算法 update; 但数据生成和人工编辑保证长程一致性与事件图 grounding。",
            "Memory retrieval": "Full Context baseline 无检索, 直接输入完整历史; RAG baseline 用检索增强; 这提供了后续论文的共同坐标系。",
            "Reasoning/generation": "模型需要回答 single-hop, multi-hop, temporal, open-domain, adversarial 等长期记忆问题。",
            "Baselines": "Long-context LLMs, RAG, human performance; 后续论文常称 Full Context/LoCoMo",
            "主结果": "论文显示 LLM 即使用 long-context 或 RAG 仍显著落后人类, 尤其在 long-range temporal/causal dynamics 上困难。",
            "消融实验": "benchmark 论文重点是数据构建和不同模型/策略比较, 不是 memory algorithm ablation。",
            "它真正的新点": "提供了整个方向的主要评估场景和 F1 口径, 是所有 LoCoMo memory 论文的共同参照。",
            "它可能的问题": "后续已有研究质疑部分标注/评价稳定性; Full Context 作为 baseline 不等价于真实可扩展 memory system。",
            "我能借鉴什么": "必须精读任务定义、问题类型、评分脚本和数据格式; 你的实验设计要对齐它。",
            "我能超过它的地方": "不是超过 benchmark, 而是比 Full Context/RAG 更低成本地回答关键问题; 还可做按问题类型误差分析。",
            "推荐精读分数_100": "100",
            "来源链接": "https://arxiv.org/abs/2402.17753",
            "代码链接": "https://github.com/snap-research/locomo",
        },
    ),
    row(
        类别="高频 baseline / 基准项",
        论文名="MemoryBank: Enhancing Large Language Models with Long-Term Memory",
        **{
            "年份/会议": "2023 arXiv; submitted 2023-05-17",
            "代码是否开源": "是/部分; GitHub commonly referenced: zhongwanjun/MemoryBank-SiliconFriend",
            "任务": "为 LLM companion/chatbot 加入长期记忆、用户画像和遗忘/强化机制。",
            "数据集": "real-world user dialogs; simulated long-term dialogs; SiliconFriend companion setting",
            "指标": "memory recall; personality understanding; empathy/response quality; qualitative + quantitative simulated dialog analysis。",
            "一句话 motivation": "长期陪伴式 AI 需要记住用户经历与偏好, 并像人一样随时间遗忘或强化记忆。",
            "它批评现有方法什么": "批评 LLM 缺少长期记忆机制, 在个人陪伴、心理咨询等持续交互场景中无法保持一致和个性化。",
            "Memory representation": "长期记忆库保存用户交互中的 facts/events/preferences/personality; 可被后续对话召回; 更偏文本/摘要式记忆。",
            "Memory update": "受 Ebbinghaus forgetting curve 启发, 按时间和记忆重要性进行遗忘与强化; 持续更新用户画像。",
            "Memory retrieval": "根据当前对话召回相关历史 memory; 侧重陪伴和个性化, 不是复杂 graph traversal。",
            "Reasoning/generation": "检索到的记忆进入 prompt, 让 chatbot 更能回忆用户信息并产生共情回应。",
            "Baselines": "Long-term companion chatbot settings; 后续 LoCoMo 论文中作为早期 memory baseline",
            "主结果": "论文展示 SiliconFriend 在长期陪伴场景中能更好 recall memories、理解用户 personality 并提升回应质量。",
            "消融实验": "主要分析遗忘曲线、记忆更新和用户画像对长期对话质量的影响; 不是现代 LoCoMo F1 式 ablation。",
            "它真正的新点": "早期把长期记忆、遗忘曲线、用户画像结合起来, 影响后续 agent memory 基础设定。",
            "它可能的问题": "结构较简单; 对多跳/时间 QA 不够强; 很多后续论文把它当老基线。",
            "我能借鉴什么": "读它主要是理解 memory 方向早期动机和 forgetting/update 机制。",
            "我能超过它的地方": "用结构化 evidence、temporal version 和 multi-hop retrieval 完全可以在 LoCoMo F1 上超过。",
            "推荐精读分数_100": "82",
            "来源链接": "https://arxiv.org/abs/2305.10250",
            "代码链接": "https://github.com/zhongwanjun/MemoryBank-SiliconFriend",
        },
    ),
    row(
        类别="高频 baseline / 基准项",
        论文名="A Human-Inspired Reading Agent with Gist Memory of Very Long Contexts / ReadAgent",
        **{
            "年份/会议": "2024 arXiv; submitted 2024-02-15",
            "代码是否开源": "部分; 有项目页与方法说明, 常被后续论文复现为 prompting baseline",
            "任务": "超长文档/上下文阅读理解; 用 gist memory 扩展有效上下文长度。",
            "数据集": "QuALITY; NarrativeQA; QMSum; 后续被迁移为 LoCoMo memory baseline",
            "指标": "long-document QA/summarization accuracy; effective context length; task-specific scores。",
            "一句话 motivation": "LLM 不只受最大上下文限制, 也不能鲁棒消化长输入; 可以模仿人类读书时形成 gist memory 并按需回看原文。",
            "它批评现有方法什么": "批评直接输入长上下文和普通检索都无法稳定处理 very long contexts; 缺少主动记 gist 和回看细节的过程。",
            "Memory representation": "把文档分成 memory episodes, 再压缩为短 episodic memories/gist memories; 同时保留原文 passage 以便 lookup。",
            "Memory update": "阅读过程中决定哪些内容组成 episode, 并生成 gist; 属于读文档时的阶段性 memory construction。",
            "Memory retrieval": "先检索/读取 gist memory, 若需要细节则采取 action 回看原文 passage; 是 gist -> raw passage 的两阶段思路。",
            "Reasoning/generation": "agent 根据 gist 和必要原文证据回答问题; 对长文档任务有效。",
            "Baselines": "retrieval methods, original long contexts, gist-only variants",
            "主结果": "论文报告 ReadAgent 在三个长文档任务上超过 baselines, 有效上下文窗口提升约 3.5-20 倍。",
            "消融实验": "比较不同读取/存储/lookup 策略和只用 gist/原文等设置; 说明 gist + lookup 组合重要。",
            "它真正的新点": "gist memory + on-demand lookup 是后续很多 raw evidence reconstruction 方法的前身。",
            "它可能的问题": "原任务是长文档阅读, 不是专门长时对话; 对动态用户状态、冲突更新处理有限。",
            "我能借鉴什么": "借鉴 gist-to-raw lookup; 你的方法可把它迁移到对话 turn/event 层。",
            "我能超过它的地方": "加入 entity/time graph 和 evidence sufficiency, 让 lookup 不只是回看, 而是有目标地补证据缺口。",
            "推荐精读分数_100": "84",
            "来源链接": "https://arxiv.org/abs/2402.09727",
            "代码链接": "https://read-agent.github.io/",
        },
    ),
    row(
        类别="高频 baseline / 基准项",
        论文名="Memory OS of AI Agent / MemoryOS",
        **{
            "年份/会议": "2025 arXiv; submitted 2025-05-30",
            "代码是否开源": "是; GitHub: BAI-LAB/MemoryOS",
            "任务": "借鉴操作系统内存管理, 为 AI agents 设计 hierarchical memory management。",
            "数据集": "LoCoMo",
            "指标": "LoCoMo F1; BLEU-1; average improvement over baselines; contextual coherence and personalization。",
            "一句话 motivation": "LLM 固定上下文窗口和记忆管理不足导致长期个性化能力短缺, 需要像 OS 一样管理不同层级记忆。",
            "它批评现有方法什么": "批评 LLM 交互是 stateless/short-context; 缺少长期记忆、动态更新和层级存储策略。",
            "Memory representation": "三层存储: short-term memory, mid-term memory, long-term personal memory; 对应不同生命周期和抽象程度。",
            "Memory update": "short-term 到 mid-term 使用 dialogue-chain-based FIFO; mid-term 到 long-term 使用 segmented page organization; 支持动态层级更新。",
            "Memory retrieval": "包含 Memory Storage, Updating, Retrieval, Generation 四模块; 根据当前 query 从不同层级召回相关 memory。",
            "Reasoning/generation": "generation 模块把召回记忆整合进回答, 强化长期 coherence 和 personalized retention。",
            "Baselines": "LoCoMo 上多个 memory baselines",
            "主结果": "论文报告在 GPT-4o-mini 上相对 baselines 平均 F1 提升约 49.11%, BLEU-1 提升约 46.18%。",
            "消融实验": "分析三层 memory、FIFO/page update、retrieval/generation 模块贡献。",
            "它真正的新点": "用 OS memory management 类比给 agent memory 一个清晰架构, 成为 2026 论文常用强 baseline。",
            "它可能的问题": "OS 类比更多是架构故事, 对 evidence sufficiency 和 multi-hop path 显式建模不足。",
            "我能借鉴什么": "借鉴 STM/MTM/LTM 分层和 update lifecycle。",
            "我能超过它的地方": "在层级召回后增加证据检查与 raw evidence recovery; 处理 state transitions 而不是简单长期页合并。",
            "推荐精读分数_100": "88",
            "来源链接": "https://arxiv.org/abs/2506.06326",
            "代码链接": "https://github.com/BAI-LAB/MemoryOS",
        },
    ),
    row(
        类别="高频 baseline / 基准项",
        论文名="LightMem: Lightweight and Efficient Memory-Augmented Generation",
        **{
            "年份/会议": "2026 ICLR; arXiv submitted 2025-10-21",
            "代码是否开源": "是; GitHub: zjunlp/LightMem",
            "任务": "轻量高效的 memory-augmented generation; 在性能和效率之间取得平衡。",
            "数据集": "Long-term memory and MAG benchmarks; 后续 LoCoMo 论文常用作 baseline",
            "指标": "task performance; memory efficiency; time/computational overhead; cost。",
            "一句话 motivation": "memory 系统能让 LLM 持久化信息, 但很多现有方法带来过高时间和计算开销。",
            "它批评现有方法什么": "批评 existing memory systems overhead 大, 在线更新/检索/利用流程不够轻量。",
            "Memory representation": "受 Atkinson-Shiffrin 模型启发, 组织为 sensory memory、topic-aware short-term memory、long-term memory; topic grouping 和 sleep-time update 是关键。",
            "Memory update": "sensory memory 快速过滤和压缩; short-term memory 按 topic consolidation; long-term memory 采用 offline sleep-time update, 把在线推理和长期整合解耦。",
            "Memory retrieval": "从结构化长期/短期记忆中检索相关 topic/memory; 重点是轻量化和减少在线成本。",
            "Reasoning/generation": "将检索到的 memory 用于 generation, 在较低开销下保持长期信息利用。",
            "Baselines": "Memory-augmented generation systems; 2026 LoCoMo 论文常与 A-Mem/Mem0/MemoryOS 并列",
            "主结果": "论文摘要强调在保持性能的同时显著降低时间和计算 overhead; ICLR 2026 版本开源。",
            "消融实验": "围绕 sensory/STM/LTM、topic grouping、sleep-time update、压缩策略做分析。",
            "它真正的新点": "把认知三阶段 memory 和工程轻量化结合, 对效率 baseline 影响很大。",
            "它可能的问题": "注意它与 2026-04-09 的 LightMem 不是同一个时间线; 对 evidence gap 和冲突处理不是重点。",
            "我能借鉴什么": "借鉴 sleep-time offline consolidation 和 topic-aware memory stage。",
            "我能超过它的地方": "用更强的问题感知检索和证据校准弥补 lightweight 方法的推理不足。",
            "推荐精读分数_100": "83",
            "来源链接": "https://arxiv.org/abs/2510.18866",
            "代码链接": "https://github.com/zjunlp/LightMem",
        },
    ),
    row(
        类别="高频 baseline / 基准项",
        论文名="MemGPT: Towards LLMs as Operating Systems",
        **{
            "年份/会议": "2023 arXiv; submitted 2023-10-12",
            "代码是否开源": "是; 原 MemGPT 代码/数据公开, 项目后续演进为 Letta 生态",
            "任务": "用 virtual context management 让 LLM 在有限上下文窗口外管理长期对话和长文档记忆。",
            "数据集": "document analysis tasks; multi-session chat; 后续 LoCoMo 论文常作为早期 memory baseline",
            "指标": "long-document analysis performance; multi-session chat memory quality; context management ability。",
            "一句话 motivation": "LLM 上下文窗口有限, 可以像操作系统分页一样在 fast/slow memory tiers 间搬运信息, 提供虚拟大上下文。",
            "它批评现有方法什么": "批评固定上下文窗口限制 LLM 处理超长文档和多会话聊天; 普通 prompt 不能主动管理内外部记忆。",
            "Memory representation": "核心 memory tiers: main context 类似快速内存, external/archival memory 类似慢速存储; 还有 core memory 保存重要 persona/state。",
            "Memory update": "LLM 通过工具调用执行 memory operations, 如 append/replace/search/insert; interrupt/control-flow 机制让模型自己管理记忆。",
            "Memory retrieval": "LLM 可主动搜索 archival/conversation memory, 把相关内容调入当前上下文; 强调 self-directed memory management。",
            "Reasoning/generation": "模型在生成过程中决定何时读写 memory, 像 OS 进程管理有限上下文。",
            "Baselines": "long-context/document analysis baselines; multi-session chat baselines",
            "主结果": "论文展示 MemGPT 能处理超过底层 LLM context window 的文档分析, 并支持能记住、反思和演化的多会话聊天 agent。",
            "消融实验": "比较不同 memory tiers、工具调用和不使用外部 memory 的设置; 强调 virtual context management 贡献。",
            "它真正的新点": "最早把 LLM memory 明确类比为 OS virtual memory, 对后续 MemOS/MemoryOS 和 agentic memory 影响很大。",
            "它可能的问题": "工具调用和自主管理成本高; 早期方法对 LoCoMo F1 不一定强; 写入检索策略较粗。",
            "我能借鉴什么": "适合读思想史和架构隐喻; 不是你最该复现的强 baseline。",
            "我能超过它的地方": "在具体 LoCoMo QA 上用更结构化的 evidence retrieval 和时间冲突处理明显更有针对性。",
            "推荐精读分数_100": "86",
            "来源链接": "https://arxiv.org/abs/2310.08560",
            "代码链接": "https://github.com/cpacker/MemGPT; https://github.com/letta-ai/letta",
        },
    ),
]


OUT_DIR.mkdir(parents=True, exist_ok=True)
with OUT_PATH.open("w", newline="", encoding="utf-8-sig") as f:
    writer = csv.DictWriter(f, fieldnames=FIELDS)
    writer.writeheader()
    writer.writerows(rows)

print(f"Wrote {len(rows)} rows to {OUT_PATH}")
