#!/usr/bin/env bash
# Shared runtime guardrails for local reproduction runs.
#
# These variables only constrain CPU-side thread pools used by BLAS, PyTorch,
# tokenizers, and related libraries. They do not change prompts, retrieval,
# model choices, metrics, or dataset rows.

export EXPERIMENT_CPU_THREADS="${EXPERIMENT_CPU_THREADS:-1}"
export EXPERIMENT_CPU_INTEROP_THREADS="${EXPERIMENT_CPU_INTEROP_THREADS:-1}"

export OMP_NUM_THREADS="${OMP_NUM_THREADS:-$EXPERIMENT_CPU_THREADS}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-$EXPERIMENT_CPU_THREADS}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-$EXPERIMENT_CPU_THREADS}"
export BLIS_NUM_THREADS="${BLIS_NUM_THREADS:-$EXPERIMENT_CPU_THREADS}"
export VECLIB_MAXIMUM_THREADS="${VECLIB_MAXIMUM_THREADS:-$EXPERIMENT_CPU_THREADS}"
export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-$EXPERIMENT_CPU_THREADS}"
export RAYON_NUM_THREADS="${RAYON_NUM_THREADS:-$EXPERIMENT_CPU_THREADS}"
export POLARS_MAX_THREADS="${POLARS_MAX_THREADS:-$EXPERIMENT_CPU_THREADS}"
export ORT_NUM_THREADS="${ORT_NUM_THREADS:-$EXPERIMENT_CPU_THREADS}"
export MALLOC_ARENA_MAX="${MALLOC_ARENA_MAX:-2}"
export OMP_WAIT_POLICY="${OMP_WAIT_POLICY:-PASSIVE}"
export KMP_BLOCKTIME="${KMP_BLOCKTIME:-0}"
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-false}"

export HF_HUB_DISABLE_TELEMETRY="${HF_HUB_DISABLE_TELEMETRY:-1}"
export MEM0_TELEMETRY="${MEM0_TELEMETRY:-False}"
