#!/usr/bin/env bash
set -uo pipefail

cd /home/stu0032/paper || exit 1
source /home/stu0032/paper/scripts/common_runtime_limits.sh

TS="${MEMORY_THREE_RERUN_TS:-$(date +%Y%m%d_%H%M%S)}"
RUN_ROOT="${MEMORY_THREE_RERUN_ROOT:-/home/stu0032/paper/runs/memgas_mem0_amem_rerun_qwen25_3b_full/$TS}"
mkdir -p "$RUN_ROOT"
MASTER_LOG="$RUN_ROOT/master.log"

log() {
  echo "[$(date '+%F %T')] $*" | tee -a "$MASTER_LOG"
}

run_step() {
  local name="$1"
  shift
  local step_log="$RUN_ROOT/$name.log"
  log "START $name"
  "$@" 2>&1 | tee "$step_log"
  local code=${PIPESTATUS[0]}
  log "END $name exit=$code log=$step_log"
  return 0
}

log "MemGAS + Mem0 + A-MEM rerun root=$RUN_ROOT"

run_step memgas \
  env MEMGAS_QA_WORKERS="${MEMGAS_QA_WORKERS:-16}" \
      MEMGAS_TOPK="${MEMGAS_TOPK:-20}" \
      MEMGAS_SUMMARY_MAX_TOKENS="${MEMGAS_SUMMARY_MAX_TOKENS:-8192}" \
      MEMGAS_ANSWER_MAX_TOKENS="${MEMGAS_ANSWER_MAX_TOKENS:-8192}" \
      MEMGAS_MAX_MODEL_TOKENS="${MEMGAS_MAX_MODEL_TOKENS:-32768}" \
      MEMGAS_TOKEN_GUARD_BUFFER="${MEMGAS_TOKEN_GUARD_BUFFER:-1536}" \
      MEMGAS_MIN_GENERATION_TOKENS="${MEMGAS_MIN_GENERATION_TOKENS:-512}" \
      MEMGAS_MAX_PROMPT_TOKENS="${MEMGAS_MAX_PROMPT_TOKENS:-12000}" \
      MEMGAS_OPENAI_TIMEOUT="${MEMGAS_OPENAI_TIMEOUT:-180}" \
      LOCOMO_MAX_MODEL_TOKENS="${LOCOMO_MAX_MODEL_TOKENS:-32768}" \
      LOCOMO_TOKEN_GUARD_BUFFER="${LOCOMO_TOKEN_GUARD_BUFFER:-1536}" \
      LOCOMO_MAX_PROMPT_TOKENS="${LOCOMO_MAX_PROMPT_TOKENS:-18000}" \
      LOCOMO_OPENAI_TIMEOUT="${LOCOMO_OPENAI_TIMEOUT:-180}" \
      LOCOMO_QA_MAX_RETRIES="${LOCOMO_QA_MAX_RETRIES:-2}" \
      MEMGAS_MAX_KEYWORDS="${MEMGAS_MAX_KEYWORDS:-64}" \
      MEMGAS_SKIP_BERTSCORE="${MEMGAS_SKIP_BERTSCORE:-0}" \
      BERTSCORE_BATCH_SIZE="${BERTSCORE_BATCH_SIZE:-2}" \
      BERTSCORE_DEVICE="${BERTSCORE_DEVICE:-cpu}" \
      bash scripts/run_memgas_qwen25_3b_full.sh

run_step mem0 \
  env MEM0_WAIT_FOR_ACTIVE_BASELINES=0 \
      MEM0_BUILD_WORKERS="${MEM0_BUILD_WORKERS:-2}" \
      MEM0_SEARCH_WORKERS="${MEM0_SEARCH_WORKERS:-2}" \
      MEM0_QA_BATCH="${MEM0_QA_BATCH:-8}" \
      MEM0_API_PARALLEL="${MEM0_API_PARALLEL:-8}" \
      MEM0_QA_MAX_TOKENS="${MEM0_QA_MAX_TOKENS:-8192}" \
      MEM0_LLM_MAX_TOKENS="${MEM0_LLM_MAX_TOKENS:-24576}" \
      LIGHTMEM_MAX_MODEL_TOKENS="${LIGHTMEM_MAX_MODEL_TOKENS:-32768}" \
      LIGHTMEM_TOKEN_GUARD_BUFFER="${LIGHTMEM_TOKEN_GUARD_BUFFER:-1536}" \
      LIGHTMEM_MIN_GENERATION_TOKENS="${LIGHTMEM_MIN_GENERATION_TOKENS:-512}" \
      LIGHTMEM_MAX_PROMPT_TOKENS="${LIGHTMEM_MAX_PROMPT_TOKENS:-12000}" \
      LIGHTMEM_OPENAI_TIMEOUT="${LIGHTMEM_OPENAI_TIMEOUT:-180}" \
      LIGHTMEM_MEM0_MAX_RETRIES="${LIGHTMEM_MEM0_MAX_RETRIES:-1}" \
      CORE_BASELINE_MAX_MODEL_TOKENS="${CORE_BASELINE_MAX_MODEL_TOKENS:-32768}" \
      CORE_BASELINE_CONTEXT_TOKEN_BUFFER="${CORE_BASELINE_CONTEXT_TOKEN_BUFFER:-1536}" \
      MEM0_SKIP_BERTSCORE="${MEM0_SKIP_BERTSCORE:-0}" \
      BERTSCORE_BATCH_SIZE="${BERTSCORE_BATCH_SIZE:-2}" \
      BERTSCORE_DEVICE="${BERTSCORE_DEVICE:-cpu}" \
      bash scripts/run_mem0_qwen25_3b_full.sh

run_step amem_official \
  env AMEM_OFFICIAL_FRESH="${AMEM_OFFICIAL_FRESH:-1}" \
      AMEM_RETRIEVE_K="${AMEM_RETRIEVE_K:-10}" \
      AMEM_LLM_MAX_TOKENS="${AMEM_LLM_MAX_TOKENS:-8192}" \
      AMEM_MAX_MODEL_TOKENS="${AMEM_MAX_MODEL_TOKENS:-32768}" \
      AMEM_TOKEN_GUARD_BUFFER="${AMEM_TOKEN_GUARD_BUFFER:-1536}" \
      AMEM_MIN_OUTPUT_TOKENS="${AMEM_MIN_OUTPUT_TOKENS:-64}" \
      AMEM_MAX_PROMPT_TOKENS="${AMEM_MAX_PROMPT_TOKENS:-8192}" \
      AMEM_OPENAI_TIMEOUT="${AMEM_OPENAI_TIMEOUT:-180}" \
      AMEM_LLM_MAX_RETRIES="${AMEM_LLM_MAX_RETRIES:-1}" \
      AMEM_SKIP_BERTSCORE="${AMEM_SKIP_BERTSCORE:-0}" \
      BERTSCORE_BATCH_SIZE="${BERTSCORE_BATCH_SIZE:-2}" \
      BERTSCORE_DEVICE="${BERTSCORE_DEVICE:-cpu}" \
      bash scripts/run_amem_official_qwen25_3b_full.sh

log "DONE all requested reruns"
