#!/usr/bin/env python3
"""Run HiGMemPlus LongDialQA with cached full-history HiGMem retrieval.

This runner preserves the evaluation surface of ``run_higmem_plus.py`` while
skipping the expensive baseline memory build/retrieval step.  It reuses a
previously generated HiGMem ``retrieved_context.jsonl`` as the base context and
then applies the HiGMemPlus retrieval layer on top of that cached base context.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
import traceback
from collections import Counter, defaultdict
from concurrent.futures import FIRST_COMPLETED, ThreadPoolExecutor, wait
from pathlib import Path
from typing import Any

from openai import OpenAI


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(ROOT / "scripts"))

from baseline.HiGMemPlus import METHODS, HiGMemPlusEnhancer  # noqa: E402
from run_higmem_plus import select_rows, to_raw_turn  # noqa: E402
from run_longdialqa_baseline import (  # noqa: E402
    append_jsonl,
    answer_with_openai,
    approx_tokens,
    build_metrics,
    build_prompt,
    context_artifact,
    distill_option,
    flatten_retrieved_scene_ids,
    load_sessions,
    load_subset_from_manifest,
    predicted_option_text,
    read_jsonl,
    retrieved_records_artifact,
    sha256_file,
    token_f1,
    turn_records_for_session,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", choices=["longdialqa"], default="longdialqa")
    parser.add_argument("--method", choices=METHODS, default="evidence_frame_routing")
    parser.add_argument("--normalized-dir", type=Path, default=Path("datasets/DialSim/longdialqa_normalized_v1.1_seed0"))
    parser.add_argument("--subset-manifest", type=Path, required=True)
    parser.add_argument(
        "--base-retrieved-context",
        type=Path,
        required=True,
        help="HiGMem retrieved_context.jsonl generated by the full-history baseline run.",
    )
    parser.add_argument("--output-dir", type=Path, default=Path("runs/higmem_plus_cached"))
    parser.add_argument("--shows", nargs="+", default=["friends", "bigbang", "theoffice"])
    parser.add_argument("--row-shard-index", type=int, default=0)
    parser.add_argument("--row-shard-count", type=int, default=1)
    parser.add_argument("--max-qa-per-show", type=int, default=None, help=argparse.SUPPRESS)
    parser.add_argument("--smoke-per-show", type=int, default=None)
    parser.add_argument("--max-questions", type=int, default=None)
    parser.add_argument("--top-k", type=int, default=10)
    parser.add_argument("--component-k", type=int, default=10)
    parser.add_argument("--edge-k", type=int, default=8)
    parser.add_argument("--episode-k", type=int, default=3)
    parser.add_argument("--model", default=os.environ.get("OPENAI_MODEL", "Qwen/Qwen2.5-3B-Instruct"))
    parser.add_argument("--api-base", default=os.environ.get("OPENAI_BASE_URL", os.environ.get("OPENAI_API_BASE", "http://127.0.0.1:8000/v1")))
    parser.add_argument("--api-key", default=os.environ.get("OPENAI_API_KEY", "EMPTY"))
    parser.add_argument("--answer-max-tokens", type=int, default=int(os.environ.get("LONGDIALQA_ANSWER_MAX_TOKENS", "32")))
    parser.add_argument("--answer-timeout", type=float, default=float(os.environ.get("LONGDIALQA_ANSWER_TIMEOUT", "120")))
    parser.add_argument("--answer-workers", type=int, default=int(os.environ.get("HIGMEM_PLUS_ANSWER_WORKERS", "16")))
    parser.add_argument("--max-pending", type=int, default=int(os.environ.get("HIGMEM_PLUS_MAX_PENDING", "64")))
    parser.add_argument("--max-context-chars", type=int, default=int(os.environ.get("HIGMEM_PLUS_MAX_CONTEXT_CHARS", "60000")))
    parser.add_argument("--max-saved-context-chars", type=int, default=int(os.environ.get("LONGDIALQA_MAX_SAVED_CONTEXT_CHARS", "20000")))
    parser.add_argument("--max-saved-records", type=int, default=int(os.environ.get("LONGDIALQA_MAX_SAVED_RECORDS", "200")))
    parser.add_argument("--resume", action="store_true")
    return parser.parse_args()


def prepare_paths(out_dir: Path, resume: bool = False) -> dict[str, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    paths = {
        "command_env": out_dir / "command.env",
        "dataset_manifest": out_dir / "dataset_manifest.json",
        "raw_predictions": out_dir / "raw_predictions.jsonl",
        "retrieved_evidence": out_dir / "retrieved_evidence.jsonl",
        "component_traces": out_dir / "component_traces.jsonl",
        "graph_traces": out_dir / "graph_traces.jsonl",
        "repair_traces": out_dir / "repair_traces.jsonl",
        "episode_traces": out_dir / "episode_traces.jsonl",
        "route_traces": out_dir / "route_traces.jsonl",
        "metrics": out_dir / "metrics.json",
        "stats": out_dir / "stats.json",
        "summary": out_dir / "summary.md",
        "run_log": out_dir / "run.log",
    }
    for key, path in paths.items():
        if (
            not resume
            and key not in {"command_env", "dataset_manifest", "metrics", "stats", "summary", "run_log"}
            and path.exists()
        ):
            path.unlink()
        if path.suffix == ".jsonl":
            path.touch()
    return paths


def save_command_env(path: Path, args: argparse.Namespace, subset_path: Path, normalized_manifest: Path) -> None:
    lines = [
        f"DATASET={args.dataset}",
        f"METHOD={args.method}",
        f"OPENAI_MODEL={args.model}",
        f"OPENAI_BASE_URL={args.api_base}",
        f"NORMALIZED_DIR={args.normalized_dir}",
        f"NORMALIZED_MANIFEST={normalized_manifest}",
        f"NORMALIZED_MANIFEST_SHA256={sha256_file(normalized_manifest)}",
        f"SUBSET_MANIFEST={args.subset_manifest}",
        f"SUBSET_MANIFEST_SHA256={sha256_file(args.subset_manifest)}",
        f"SUBSET_PATH={subset_path}",
        f"SUBSET_SHA256={sha256_file(subset_path)}",
        f"BASE_RETRIEVED_CONTEXT={args.base_retrieved_context}",
        f"BASE_RETRIEVED_CONTEXT_SHA256={sha256_file(args.base_retrieved_context)}",
        f"SHOWS={','.join(args.shows)}",
        f"ROW_SHARD_INDEX={args.row_shard_index}",
        f"ROW_SHARD_COUNT={args.row_shard_count}",
        f"SMOKE_PER_SHOW={args.smoke_per_show}",
        f"MAX_QUESTIONS={args.max_questions}",
        f"TOP_K={args.top_k}",
        f"COMPONENT_K={args.component_k}",
        f"EDGE_K={args.edge_k}",
        f"EPISODE_K={args.episode_k}",
        f"ANSWER_MAX_TOKENS={args.answer_max_tokens}",
        f"ANSWER_TIMEOUT={args.answer_timeout}",
        f"ANSWER_WORKERS={args.answer_workers}",
        f"MAX_PENDING={args.max_pending}",
        f"MAX_CONTEXT_CHARS={args.max_context_chars}",
        "COMMAND=" + " ".join(sys.argv),
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def load_base_cache(path: Path) -> dict[str, dict[str, Any]]:
    cache: dict[str, dict[str, Any]] = {}
    for row in read_jsonl(path):
        qa_id = str(row.get("qa_id") or "")
        if qa_id:
            cache[qa_id] = row
    return cache


def base_context_from_cache(row: dict[str, Any]) -> tuple[str, list[dict[str, Any]], dict[str, Any]]:
    records = list(row.get("retrieved_records") or [])
    context = str(row.get("context") or "")
    reconstructed = False
    if not context and records:
        if len(records) == 1 and records[0].get("used_content") is not None:
            context = str(records[0].get("used_content") or "")
            reconstructed = True
        else:
            context = "\n\n".join(str(record.get("used_content") or "") for record in records if record.get("used_content"))
            reconstructed = True
    if not records:
        records = [{"used_content": context, "metadata": {"scene_ids_in_text": []}}]
    stats = dict(row.get("retrieval_stats") or {})
    stats.update(
        {
            "cache_context_chars": int(row.get("context_chars") or len(context or "")),
            "cache_context_truncated_for_artifact": bool(row.get("context_truncated_for_artifact")),
            "cache_context_reconstructed_from_records": reconstructed,
            "cache_source": "retrieved_context",
        }
    )
    return context, records, stats


def build_retrieval_item(
    *,
    row: dict[str, Any],
    enhancer: HiGMemPlusEnhancer,
    args: argparse.Namespace,
    cache_row: dict[str, Any],
) -> dict[str, Any]:
    qa_started = time.time()
    retrieval_started = time.time()
    base_context, base_records, base_stats = base_context_from_cache(cache_row)
    if args.method == "baseline_higmem":
        plus_result = enhancer.retrieve(
            question=row["question"],
            base_context=base_context,
            base_records=base_records,
            metadata={**row, "dataset": "longdialqa"},
        )
        context = base_context[: args.max_context_chars] if args.max_context_chars > 0 else base_context
        retrieved_records = base_records
    else:
        plus_result = enhancer.retrieve(
            question=row["question"],
            base_context=base_context,
            base_records=base_records,
            metadata={**row, "dataset": "longdialqa"},
        )
        context = plus_result.context
        retrieved_records = plus_result.evidence_records
    retrieval_seconds = time.time() - retrieval_started

    retrieved_scene_ids = flatten_retrieved_scene_ids(retrieved_records)
    evidence_scene_ids = [str(item) for item in row.get("evidence_scene_ids") or []]
    has_evidence = bool(evidence_scene_ids)
    evidence_recall_any = bool(has_evidence and set(evidence_scene_ids).intersection(retrieved_scene_ids))
    evidence_recall_all = bool(has_evidence and set(evidence_scene_ids).issubset(set(retrieved_scene_ids)))
    prompt = build_prompt(row, context)
    common = {
        "method": args.method,
        "baseline": "higmem_cached_full_history",
        "qa_id": row["id"],
        "show": row["show"],
        "show_name": row["show_name"],
        "episode_id": row["episode_id"],
        "scene_id": row["scene_id"],
        "session_ordinal": row["session_ordinal"],
        "question": row["question"],
        "question_prompt": row["question_prompt"],
        "question_source": row["question_source"],
        "question_type": row["question_type"],
        "answerability_label": "answerable" if row["answerable"] else "unanswerable",
        "hop_type": row["hop_type"],
        "gold_option": row["gold_option"],
        "gold_answer": row["answer"],
        "retrieved_k": len(retrieved_records),
        "retrieved_context_chars": len(context or ""),
        "retrieved_context_tokens_approx": approx_tokens(context or ""),
        "retrieved_scene_ids": retrieved_scene_ids,
        "evidence_scene_ids": evidence_scene_ids,
        "has_evidence_scene": has_evidence,
        "evidence_recall_any": evidence_recall_any,
        "evidence_recall_all": evidence_recall_all,
        "retrieval_seconds": retrieval_seconds,
        "method_stats": {"base_stats": base_stats, "plus_stats": plus_result.stats},
    }
    retrieved_row = {
        **{key: common[key] for key in ["method", "qa_id", "show", "show_name", "question", "question_type"]},
        **context_artifact(context, args.max_saved_context_chars),
        **retrieved_records_artifact(retrieved_records, args.max_saved_records),
        "retrieved_scene_ids": retrieved_scene_ids,
        "evidence_scene_ids": evidence_scene_ids,
        "evidence_recall_any": evidence_recall_any,
        "evidence_recall_all": evidence_recall_all,
    }
    return {
        "row": row,
        "prompt": prompt,
        "qa_started": qa_started,
        "common": common,
        "retrieved_evidence": retrieved_row,
        "component_trace": plus_result.component_trace,
        "graph_trace": plus_result.graph_trace,
        "repair_trace": plus_result.repair_trace,
        "episode_trace": plus_result.episode_trace,
        "route_trace": plus_result.route_trace,
    }


def answer_item(item: dict[str, Any], args: argparse.Namespace) -> dict[str, Any]:
    client = OpenAI(api_key=args.api_key, base_url=args.api_base, max_retries=0)
    row = item["row"]
    answer_started = time.time()
    answer, usage, error = answer_with_openai(client, args, item["prompt"])
    answer_seconds = time.time() - answer_started
    predicted_option, ambiguous = distill_option(answer)
    strict_correct = bool(predicted_option and predicted_option == row["gold_option"] and not ambiguous)
    correct = strict_correct
    if not predicted_option and row["gold_option"] == "(E)":
        lowered = answer.lower()
        if "don't know" in lowered or "cannot answer" in lowered or "insufficient" in lowered or "not enough" in lowered:
            predicted_option = "(E)"
            correct = True
    pred_text = predicted_option_text(predicted_option, row["options"], answer)
    common = dict(item["common"])
    common.update(
        {
            "prediction": answer,
            "answer_error": error,
            "predicted_option": predicted_option,
            "predicted_answer_text": pred_text,
            "ambiguous": ambiguous,
            "strict_correct": strict_correct,
            "correct": correct,
            "token_f1": token_f1(pred_text, row["answer"]),
            "latency_seconds": time.time() - item["qa_started"],
            "answer_seconds": answer_seconds,
            "answer_token_usage": usage,
        }
    )
    failures = []
    if error:
        failures.append({"qa_id": row["id"], "stage": "answer", "error": error})
    return {
        "prediction": common,
        "retrieved_evidence": item["retrieved_evidence"],
        "component_trace": item["component_trace"],
        "graph_trace": item["graph_trace"],
        "repair_trace": item["repair_trace"],
        "episode_trace": item["episode_trace"],
        "route_trace": item["route_trace"],
        "failures": failures,
        "usage": usage,
    }


def evaluate(args: argparse.Namespace) -> dict[str, Any]:
    args.openai_base_url = args.api_base
    args.openai_api_key = args.api_key
    normalized_manifest = args.normalized_dir / "manifest.json"
    sessions_path = args.normalized_dir / "sessions.jsonl"
    all_rows, subset_path, subset_manifest = load_subset_from_manifest(args)
    selected_rows = select_rows(all_rows, args)
    selected_ids = {str(row["id"]) for row in selected_rows}
    base_cache = load_base_cache(args.base_retrieved_context)
    missing = sorted(selected_ids - set(base_cache))
    if missing:
        raise ValueError(f"Base retrieved-context cache is missing {len(missing)} selected QA ids; first missing: {missing[:5]}")

    sessions = load_sessions(sessions_path)
    out_dir = args.output_dir / args.method
    paths = prepare_paths(out_dir, resume=args.resume)
    save_command_env(paths["command_env"], args, subset_path, normalized_manifest)
    dataset_manifest = {
        "dataset": "LongDialQA/DialSim",
        "method": args.method,
        "normalized_manifest": str(normalized_manifest),
        "normalized_manifest_sha256": sha256_file(normalized_manifest),
        "subset_manifest": str(args.subset_manifest),
        "subset_manifest_sha256": sha256_file(args.subset_manifest),
        "subset_path": str(subset_path),
        "subset_sha256": sha256_file(subset_path),
        "base_retrieved_context": str(args.base_retrieved_context),
        "base_retrieved_context_sha256": sha256_file(args.base_retrieved_context),
        "source_subset_rows": len(all_rows),
        "selected_rows": len(selected_rows),
        "shows_filter": list(args.shows),
        "row_shard_index": args.row_shard_index,
        "row_shard_count": args.row_shard_count,
        "smoke_per_show": args.smoke_per_show,
        "max_questions": args.max_questions,
        "selected_qa_ids": [row["id"] for row in selected_rows],
        "source_manifest": subset_manifest,
        "cached_base_context": True,
        "answer_workers": args.answer_workers,
        "max_pending": args.max_pending,
    }
    paths["dataset_manifest"].write_text(json.dumps(dataset_manifest, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8")

    predictions: list[dict[str, Any]] = []
    if args.resume and paths["raw_predictions"].exists():
        predictions = [row for row in read_jsonl(paths["raw_predictions"]) if str(row.get("qa_id")) in selected_ids]
    completed_ids = {
        str(row.get("qa_id"))
        for row in predictions
        if row.get("qa_id") and not row.get("answer_error") and str(row.get("prediction") or "").strip()
    }
    failures: list[dict[str, Any]] = []
    stats: dict[str, Any] = {
        "method": args.method,
        "started_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "selected_rows": len(selected_rows),
        "source_subset_rows": len(all_rows),
        "answer_workers": args.answer_workers,
        "max_pending": args.max_pending,
        "base_retrieved_context": str(args.base_retrieved_context),
        "token_usage": Counter(),
        "shows": {},
        "cache": {
            "entries": len(base_cache),
            "selected_hits": len(selected_rows),
            "selected_missing": 0,
        },
    }
    started = time.time()

    subset_by_show: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in selected_rows:
        subset_by_show[str(row["show"])].append(row)
    for show_rows in subset_by_show.values():
        show_rows.sort(key=lambda row: (int(row["session_ordinal"]), int(row["ask_turn_index"]), str(row["id"])))

    pending: dict[Any, dict[str, Any]] = {}
    max_pending = max(1, args.max_pending)

    def emit_result(result: dict[str, Any]) -> None:
        common = result["prediction"]
        predictions.append(common)
        append_jsonl(paths["raw_predictions"], common)
        append_jsonl(paths["retrieved_evidence"], result["retrieved_evidence"])
        stats["token_usage"].update(result.get("usage") or {})
        for failure in result.get("failures") or []:
            failures.append(failure)
            append_jsonl(paths["run_log"], {"failure": failure})
        for trace_key, trace_path in [
            ("component_trace", paths["component_traces"]),
            ("graph_trace", paths["graph_traces"]),
            ("repair_trace", paths["repair_traces"]),
            ("episode_trace", paths["episode_traces"]),
            ("route_trace", paths["route_traces"]),
        ]:
            append_jsonl(trace_path, {"qa_id": common["qa_id"], "method": args.method, "trace": result[trace_key]})

    def emit_failure(row: dict[str, Any], exc: BaseException, qa_started: float) -> None:
        failure = {
            "qa_id": row.get("id"),
            "stage": "qa",
            "error": f"{type(exc).__name__}: {exc}",
            "traceback": traceback.format_exc(),
        }
        failures.append(failure)
        append_jsonl(paths["run_log"], {"failure": failure})
        failed_prediction = {
            "method": args.method,
            "baseline": "higmem_cached_full_history",
            "qa_id": row.get("id"),
            "show": row.get("show"),
            "show_name": row.get("show_name"),
            "question": row.get("question"),
            "question_source": row.get("question_source"),
            "question_type": row.get("question_type"),
            "answerability_label": "answerable" if row.get("answerable") else "unanswerable",
            "hop_type": row.get("hop_type"),
            "gold_option": row.get("gold_option"),
            "gold_answer": row.get("answer"),
            "prediction": "",
            "answer_error": f"{type(exc).__name__}: {exc}",
            "predicted_option": "",
            "predicted_answer_text": "",
            "ambiguous": False,
            "strict_correct": False,
            "correct": False,
            "token_f1": 0.0,
            "retrieved_k": 0,
            "retrieved_context_chars": 0,
            "retrieved_context_tokens_approx": 0,
            "retrieved_scene_ids": [],
            "evidence_scene_ids": row.get("evidence_scene_ids") or [],
            "has_evidence_scene": bool(row.get("evidence_scene_ids")),
            "evidence_recall_any": False,
            "evidence_recall_all": False,
            "latency_seconds": time.time() - qa_started,
        }
        predictions.append(failed_prediction)
        append_jsonl(paths["raw_predictions"], failed_prediction)

    def drain(block: bool = False) -> None:
        if not pending:
            return
        done, _not_done = wait(
            pending,
            return_when=FIRST_COMPLETED,
            timeout=None if block else 0,
        )
        for future in done:
            item = pending.pop(future)
            try:
                emit_result(future.result())
            except Exception as exc:  # noqa: BLE001
                emit_failure(item["row"], exc, item.get("qa_started", time.time()))

    with ThreadPoolExecutor(max_workers=max(1, args.answer_workers)) as answer_pool:
        for show, qa_rows in sorted(subset_by_show.items()):
            show_started = time.time()
            enhancer = HiGMemPlusEnhancer(
                dataset="longdialqa",
                method=args.method,
                component_k=args.component_k,
                edge_k=args.edge_k,
                episode_k=args.episode_k,
                max_context_chars=args.max_context_chars,
            )
            show_sessions = sessions[show]
            next_session_idx = 0
            next_turn_idx_in_session = 0
            scheduled = 0

            def feed_until(target_session_ordinal: int, target_turn_index: int) -> None:
                nonlocal next_session_idx, next_turn_idx_in_session
                while next_session_idx < len(show_sessions):
                    session = show_sessions[next_session_idx]
                    session_ordinal = int(session["session_ordinal"])
                    turns = turn_records_for_session(session)
                    if session_ordinal < target_session_ordinal:
                        while next_turn_idx_in_session < len(turns):
                            enhancer.add_turn(to_raw_turn(turns[next_turn_idx_in_session]))
                            next_turn_idx_in_session += 1
                        next_session_idx += 1
                        next_turn_idx_in_session = 0
                        continue
                    if session_ordinal == target_session_ordinal:
                        limit = min(target_turn_index, len(turns))
                        while next_turn_idx_in_session < limit:
                            enhancer.add_turn(to_raw_turn(turns[next_turn_idx_in_session]))
                            next_turn_idx_in_session += 1
                        return
                    return

            for row in qa_rows:
                qa_started = time.time()
                try:
                    feed_until(int(row["session_ordinal"]), int(row["ask_turn_index"]))
                    if str(row["id"]) in completed_ids:
                        continue
                    item = build_retrieval_item(
                        row=row,
                        enhancer=enhancer,
                        args=args,
                        cache_row=base_cache[str(row["id"])],
                    )
                    future = answer_pool.submit(answer_item, item, args)
                    pending[future] = item
                    scheduled += 1
                    if len(pending) >= max_pending:
                        drain(block=True)
                    else:
                        drain(block=False)
                except Exception as exc:  # noqa: BLE001
                    emit_failure(row, exc, qa_started)

            stats["shows"][show] = {
                "qa_rows": len(qa_rows),
                "scheduled": scheduled,
                "seconds_before_answer_drain": time.time() - show_started,
                "turns_in_store": enhancer.store.to_manifest(),
            }
            append_jsonl(paths["run_log"], {"show_scheduled": show, "stats": stats["shows"][show]})

        while pending:
            drain(block=True)

    stats["finished_at"] = time.strftime("%Y-%m-%dT%H:%M:%S%z")
    stats["runtime_seconds"] = time.time() - started
    stats["token_usage"] = dict(stats["token_usage"])
    stats["failures"] = failures
    metrics = build_metrics(predictions)
    metrics["artifact_paths"] = {key: str(path) for key, path in paths.items()}
    metrics["dataset"] = dataset_manifest
    paths["metrics"].write_text(json.dumps(metrics, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8")
    paths["stats"].write_text(json.dumps(stats, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8")
    paths["summary"].write_text(
        "\n".join(
            [
                f"# Cached HiGMemPlus {args.method} LongDialQA/DialSim",
                "",
                f"- Method: `{args.method}`",
                f"- Selected rows: {len(selected_rows)}",
                f"- Cached base context: `{args.base_retrieved_context}`",
                f"- Answer workers: {args.answer_workers}",
                f"- Accuracy: {metrics['overall'].get('accuracy')}",
                f"- Mean retrieved K: {metrics['overall'].get('mean_retrieved_k')}",
                f"- Mean retrieved tokens approx: {metrics['overall'].get('mean_context_tokens_approx')}",
                f"- Runtime seconds: {stats['runtime_seconds']}",
                f"- Raw predictions: `{paths['raw_predictions']}`",
                f"- Retrieved evidence: `{paths['retrieved_evidence']}`",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    return {"metrics": metrics, "stats": stats}


def main() -> int:
    args = parse_args()
    result = evaluate(args)
    print(
        json.dumps(
            {
                "method": args.method,
                "overall": result["metrics"]["overall"],
                "runtime_seconds": result["stats"]["runtime_seconds"],
                "output_dir": str(args.output_dir / args.method),
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
