#!/usr/bin/env bash
set -euo pipefail

cd /home/stu0032/paper
source /home/stu0032/paper/scripts/common_runtime_limits.sh
source /home/stu0032/paper/scripts/high_utilization_runtime.sh

unset HTTP_PROXY HTTPS_PROXY ALL_PROXY http_proxy https_proxy all_proxy
export NO_PROXY="${NO_PROXY:-*}"
export no_proxy="${no_proxy:-*}"
export OPENAI_API_KEY="${OPENAI_API_KEY:-EMPTY}"
export OPENAI_BASE_URL="${OPENAI_BASE_URL:-http://127.0.0.1:8000/v1}"
export OPENAI_API_BASE="${OPENAI_API_BASE:-$OPENAI_BASE_URL}"
export OPENAI_MODEL="${OPENAI_MODEL:-Qwen/Qwen2.5-3B-Instruct}"

if [ "${MEM0_WAIT_FOR_ACTIVE_BASELINES:-1}" = "1" ]; then
  WAIT_PATTERN='[r]un_three_qwen25_3b_baselines|[r]un_simplemem_qwen25_3b_full|[r]un_memgas_qwen25_3b_full|[r]un_amem_official_qwen25_3b_full|[t]est_locomo10.py|[t]est_advanced_robust.py'
  while pgrep -af "$WAIT_PATTERN" >/dev/null; do
    echo "[$(date '+%F %T')] waiting for current baseline run to finish..."
    sleep 60
  done
fi

if locomo_high_util_enabled; then
  locomo_raise_env_int MEM0_SEARCH_WORKERS 16
  locomo_raise_env_int MEM0_API_PARALLEL 24
  locomo_raise_env_int MEM0_QA_BATCH 24
  locomo_enable_high_util_vllm_defaults
fi

locomo_set_vllm_model_path_for_openai_model
export VLLM_SERVED_MODEL="$OPENAI_MODEL"
export VLLM_ALT_SERVED_MODEL="${OPENAI_MODEL##*/}"
locomo_start_vllm_with_safe_fallback

TS="${MEM0_TS:-$(date +%Y%m%d_%H%M%S)}"
if [[ -n "${MEM0_RUN_ROOT:-}" ]]; then
  RUN_ROOT="$MEM0_RUN_ROOT"
elif [[ -n "${CORE_BASELINE_RUN_ROOT:-}" ]]; then
  RUN_ROOT="$CORE_BASELINE_RUN_ROOT"
else
  RUN_ROOT="/home/stu0032/paper/runs/mem0/qwen25_3b_full/$TS"
fi
LOG_DIR="$RUN_ROOT"
mkdir -p "$LOG_DIR" "$RUN_ROOT"
LOG_FILE="$RUN_ROOT/run.log"

export CORE_BASELINE_TS="$TS"
export CORE_BASELINE_RUN_ROOT="$RUN_ROOT"
export CORE_BASELINE_START_IDX="${CORE_BASELINE_START_IDX:-0}"
export CORE_BASELINE_END_IDX="${CORE_BASELINE_END_IDX:-10}"
export CORE_BASELINE_EXPECTED_TRAJECTORIES="${CORE_BASELINE_EXPECTED_TRAJECTORIES:-10}"
export CORE_BASELINE_EXPECTED_QA_COUNT="${CORE_BASELINE_EXPECTED_QA_COUNT:-1540}"

# Mem0's local embedding + sqlite/qdrant writes slow down badly with too many
# concurrent trajectories. Keep construction conservative; QA can still batch
# requests through vLLM without changing the evaluation protocol.
export CORE_BASELINE_BUILD_WORKERS="${MEM0_BUILD_WORKERS:-1}"
export CORE_BASELINE_SEARCH_WORKERS="${MEM0_SEARCH_WORKERS:-2}"
export CORE_BASELINE_ISOLATE_BUILD="${CORE_BASELINE_ISOLATE_BUILD:-1}"
export CORE_BASELINE_API_PARALLEL="${MEM0_API_PARALLEL:-8}"
export CORE_BASELINE_QA_BATCH="${MEM0_QA_BATCH:-8}"
export CORE_BASELINE_TOPK_MEMORY="${MEM0_TOPK:-40}"
export CORE_BASELINE_QA_MAX_TOKENS="${MEM0_QA_MAX_TOKENS:-8192}"
export CORE_BASELINE_MAX_MODEL_TOKENS="${CORE_BASELINE_MAX_MODEL_TOKENS:-32768}"
export CORE_BASELINE_CONTEXT_TOKEN_BUFFER="${CORE_BASELINE_CONTEXT_TOKEN_BUFFER:-1024}"
export CORE_BASELINE_FORCE_METRICS="${CORE_BASELINE_FORCE_METRICS:-1}"

export MEM0_LLM_MAX_TOKENS="${MEM0_LLM_MAX_TOKENS:-24576}"
export LIGHTMEM_OPENAI_TIMEOUT="${LIGHTMEM_OPENAI_TIMEOUT:-180}"
export LIGHTMEM_MEM0_MAX_RETRIES="${LIGHTMEM_MEM0_MAX_RETRIES:-1}"
export LIGHTMEM_MIN_GENERATION_TOKENS="${LIGHTMEM_MIN_GENERATION_TOKENS:-512}"
export LIGHTMEM_MEM0_STRICT_ADD="${LIGHTMEM_MEM0_STRICT_ADD:-0}"
export LIGHTMEM_MEM0_STRICT_SEARCH="${LIGHTMEM_MEM0_STRICT_SEARCH:-1}"
export LIGHTMEM_MEM0_REQUIRE_NONEMPTY="${LIGHTMEM_MEM0_REQUIRE_NONEMPTY:-1}"

export CORE_BASELINE_SKIP_BERTSCORE="${MEM0_SKIP_BERTSCORE:-0}"
export CORE_BASELINE_BERTSCORE_MODEL="${BERTSCORE_MODEL:-roberta-large}"
export CORE_BASELINE_BERTSCORE_BATCH_SIZE="${BERTSCORE_BATCH_SIZE:-2}"
export CORE_BASELINE_BERTSCORE_DEVICE="${BERTSCORE_DEVICE:-cpu}"
export CORE_BASELINE_BERTSCORE_NUM_LAYERS="${BERTSCORE_NUM_LAYERS:-17}"
export CORE_BASELINE_FAIL_ON_BERTSCORE_ERROR="${CORE_BASELINE_FAIL_ON_BERTSCORE_ERROR:-1}"

cat > "$RUN_ROOT/command.env" <<EOF
OPENAI_MODEL=$OPENAI_MODEL
OPENAI_BASE_URL=$OPENAI_BASE_URL
CORE_BASELINE_RUN_ROOT=$RUN_ROOT
CORE_BASELINE_START_IDX=$CORE_BASELINE_START_IDX
CORE_BASELINE_END_IDX=$CORE_BASELINE_END_IDX
CORE_BASELINE_EXPECTED_QA_COUNT=$CORE_BASELINE_EXPECTED_QA_COUNT
CORE_BASELINE_BUILD_WORKERS=$CORE_BASELINE_BUILD_WORKERS
CORE_BASELINE_SEARCH_WORKERS=$CORE_BASELINE_SEARCH_WORKERS
CORE_BASELINE_API_PARALLEL=$CORE_BASELINE_API_PARALLEL
CORE_BASELINE_QA_BATCH=$CORE_BASELINE_QA_BATCH
CORE_BASELINE_TOPK_MEMORY=$CORE_BASELINE_TOPK_MEMORY
CORE_BASELINE_QA_MAX_TOKENS=$CORE_BASELINE_QA_MAX_TOKENS
CORE_BASELINE_MAX_MODEL_TOKENS=$CORE_BASELINE_MAX_MODEL_TOKENS
CORE_BASELINE_CONTEXT_TOKEN_BUFFER=$CORE_BASELINE_CONTEXT_TOKEN_BUFFER
LOCOMO_HIGH_UTILIZATION_AFTER_AMEM=${LOCOMO_HIGH_UTILIZATION_AFTER_AMEM:-1}
VLLM_MODEL_PATH=$VLLM_MODEL_PATH
VLLM_GPU_MEMORY_UTILIZATION=${VLLM_GPU_MEMORY_UTILIZATION:-}
VLLM_MAX_MODEL_LEN=${VLLM_MAX_MODEL_LEN:-}
VLLM_GENERATION_CONFIG=${VLLM_GENERATION_CONFIG:-}
VLLM_DEFAULT_CHAT_TEMPLATE_KWARGS=${VLLM_DEFAULT_CHAT_TEMPLATE_KWARGS:-}
VLLM_MAX_NUM_SEQS=${VLLM_MAX_NUM_SEQS:-}
VLLM_MAX_NUM_BATCHED_TOKENS=${VLLM_MAX_NUM_BATCHED_TOKENS:-}
MEM0_LLM_MAX_TOKENS=$MEM0_LLM_MAX_TOKENS
LIGHTMEM_OPENAI_TIMEOUT=$LIGHTMEM_OPENAI_TIMEOUT
LIGHTMEM_MEM0_MAX_RETRIES=$LIGHTMEM_MEM0_MAX_RETRIES
BERTSCORE_MODEL=$CORE_BASELINE_BERTSCORE_MODEL
BERTSCORE_BATCH_SIZE=$CORE_BASELINE_BERTSCORE_BATCH_SIZE
BERTSCORE_DEVICE=$CORE_BASELINE_BERTSCORE_DEVICE
BERTSCORE_NUM_LAYERS=$CORE_BASELINE_BERTSCORE_NUM_LAYERS
EOF

echo "Mem0 LoCoMo10 Qwen2.5-3B run"
echo "Run root: $RUN_ROOT"
echo "Log:      $LOG_FILE"
echo "Workers:  build=$CORE_BASELINE_BUILD_WORKERS search=$CORE_BASELINE_SEARCH_WORKERS qa_batch=$CORE_BASELINE_QA_BATCH api_parallel=$CORE_BASELINE_API_PARALLEL"
echo "Metrics:  bertscore_skip=$CORE_BASELINE_SKIP_BERTSCORE bertscore_device=$CORE_BASELINE_BERTSCORE_DEVICE"

bash scripts/run_locomo_fixed_missing_baselines_qwen25_3b.sh MemZero 2>&1 | tee "$LOG_FILE"
